# Auto-generated filtered item list
# INPUT_FILE = 'lists/screening_super_full.py'
# INCLUDE_STRINGS = []
# EXCLUDE_STRINGS = ['Sticker |', 'Patch |', 'Battle-Scarred', 'Factory New', 'Field-Tested', 'Minimal Wear', 'Well-Worn', 'StatTrak™', 'Souvenir', 'Graffiti', 'Sticker Slab', 'Key']

ITEMS = [
    "'Blueberries' Buckshot | NSWC SEAL",
    "'Medium Rare' Crasswater | Guerrilla Warfare",
    "'The Doctor' Romanov | Sabre",
    "'Two Times' McCoy | TACP Cavalry",
    "'Two Times' McCoy | USAF TACP",
    "10 Year Birthday Sticker Capsule",
    "1st Lieutenant Farlow | SWAT",
    "2020 RMR Challengers",
    "2020 RMR Contenders",
    "2020 RMR Legends",
    "2021 Community Sticker Capsule",
    "3rd Commando Company | KSK",
    "Aces High Pin",
    "Alyx Pin",
    "Ambush Sticker Capsule",
    "Antwerp 2022 Challengers Autograph Capsule",
    "Antwerp 2022 Challengers Sticker Capsule",
    "Antwerp 2022 Champions Autograph Capsule",
    "Antwerp 2022 Contenders Autograph Capsule",
    "Antwerp 2022 Contenders Sticker Capsule",
    "Antwerp 2022 Legends Autograph Capsule",
    "Antwerp 2022 Legends Sticker Capsule",
    "Antwerp 2022 Viewer Pass",
    "Anubis Collection Package",
    "Arno The Overgrown | Guerrilla Warfare",
    "Aspirant | Gendarmerie Nationale",
    "Atlanta 2017 Challengers (Holo-Foil)",
    "Atlanta 2017 Legends (Holo-Foil)",
    "Audience Participation Parcel",
    "Austin 2025 Challengers Autograph Capsule",
    "Austin 2025 Challengers Sticker Capsule",
    "Austin 2025 Champions Autograph Capsule",
    "Austin 2025 Contenders Autograph Capsule",
    "Austin 2025 Contenders Sticker Capsule",
    "Austin 2025 Legends Autograph Capsule",
    "Austin 2025 Legends Sticker Capsule",
    "Austin 2025 Viewer Pass",
    "Autograph Capsule | Astralis | Atlanta 2017",
    "Autograph Capsule | Astralis | Cologne 2016",
    "Autograph Capsule | Astralis | MLG Columbus 2016",
    "Autograph Capsule | Challengers (Foil) | Atlanta 2017",
    "Autograph Capsule | Challengers (Foil) | Cluj-Napoca 2015",
    "Autograph Capsule | Challengers (Foil) | Cologne 2016",
    "Autograph Capsule | Challengers (Foil) | MLG Columbus 2016",
    "Autograph Capsule | Cloud9 G2A | Cologne 2015",
    "Autograph Capsule | Cloud9 | Cluj-Napoca 2015",
    "Autograph Capsule | Cloud9 | MLG Columbus 2016",
    "Autograph Capsule | Counter Logic Gaming | Cluj-Napoca 2015",
    "Autograph Capsule | Counter Logic Gaming | Cologne 2015",
    "Autograph Capsule | Counter Logic Gaming | Cologne 2016",
    "Autograph Capsule | Counter Logic Gaming | MLG Columbus 2016",
    "Autograph Capsule | FaZe Clan | Atlanta 2017",
    "Autograph Capsule | FaZe Clan | Cologne 2016",
    "Autograph Capsule | FaZe Clan | MLG Columbus 2016",
    "Autograph Capsule | Flipsid3 Tactics | Atlanta 2017",
    "Autograph Capsule | Flipsid3 Tactics | Cluj-Napoca 2015",
    "Autograph Capsule | Flipsid3 Tactics | Cologne 2015",
    "Autograph Capsule | Flipsid3 Tactics | Cologne 2016",
    "Autograph Capsule | Flipsid3 Tactics | MLG Columbus 2016",
    "Autograph Capsule | Fnatic | Atlanta 2017",
    "Autograph Capsule | Fnatic | Cluj-Napoca 2015",
    "Autograph Capsule | Fnatic | Cologne 2015",
    "Autograph Capsule | Fnatic | Cologne 2016",
    "Autograph Capsule | Fnatic | MLG Columbus 2016",
    "Autograph Capsule | G2 Esports | Atlanta 2017",
    "Autograph Capsule | G2 Esports | Cluj-Napoca 2015",
    "Autograph Capsule | G2 Esports | Cologne 2016",
    "Autograph Capsule | G2 Esports | MLG Columbus 2016",
    "Autograph Capsule | GODSENT | Atlanta 2017",
    "Autograph Capsule | Gambit Gaming | Atlanta 2017",
    "Autograph Capsule | Gambit Gaming | Cologne 2016",
    "Autograph Capsule | Gambit Gaming | MLG Columbus 2016",
    "Autograph Capsule | Group A (Foil) | Cologne 2015",
    "Autograph Capsule | Group B (Foil) | Cologne 2015",
    "Autograph Capsule | Group C (Foil) | Cologne 2015",
    "Autograph Capsule | Group D (Foil) | Cologne 2015",
    "Autograph Capsule | HellRaisers | Atlanta 2017",
    "Autograph Capsule | Legends (Foil) | Atlanta 2017",
    "Autograph Capsule | Legends (Foil) | Cluj-Napoca 2015",
    "Autograph Capsule | Legends (Foil) | Cologne 2016",
    "Autograph Capsule | Legends (Foil) | MLG Columbus 2016",
    "Autograph Capsule | Luminosity Gaming | Cluj-Napoca 2015",
    "Autograph Capsule | Luminosity Gaming | Cologne 2015",
    "Autograph Capsule | Luminosity Gaming | MLG Columbus 2016",
    "Autograph Capsule | Natus Vincere | Atlanta 2017",
    "Autograph Capsule | Natus Vincere | Cluj-Napoca 2015",
    "Autograph Capsule | Natus Vincere | Cologne 2015",
    "Autograph Capsule | Natus Vincere | Cologne 2016",
    "Autograph Capsule | Natus Vincere | MLG Columbus 2016",
    "Autograph Capsule | Ninjas in Pyjamas | Cluj-Napoca 2015",
    "Autograph Capsule | Ninjas in Pyjamas | Cologne 2015",
    "Autograph Capsule | Ninjas in Pyjamas | Cologne 2016",
    "Autograph Capsule | Ninjas in Pyjamas | MLG Columbus 2016",
    "Autograph Capsule | North | Atlanta 2017",
    "Autograph Capsule | OpTic Gaming | Atlanta 2017",
    "Autograph Capsule | OpTic Gaming | Cologne 2016",
    "Autograph Capsule | Renegades | Cologne 2015",
    "Autograph Capsule | SK Gaming | Atlanta 2017",
    "Autograph Capsule | SK Gaming | Cologne 2016",
    "Autograph Capsule | Splyce | MLG Columbus 2016",
    "Autograph Capsule | Team Dignitas | Cluj-Napoca 2015",
    "Autograph Capsule | Team Dignitas | Cologne 2016",
    "Autograph Capsule | Team EnVyUs | Atlanta 2017",
    "Autograph Capsule | Team EnVyUs | Cluj-Napoca 2015",
    "Autograph Capsule | Team EnVyUs | Cologne 2015",
    "Autograph Capsule | Team EnVyUs | Cologne 2016",
    "Autograph Capsule | Team EnVyUs | MLG Columbus 2016",
    "Autograph Capsule | Team Immunity | Cologne 2015",
    "Autograph Capsule | Team Kinguin | Cologne 2015",
    "Autograph Capsule | Team Liquid | Atlanta 2017",
    "Autograph Capsule | Team Liquid | Cluj-Napoca 2015",
    "Autograph Capsule | Team Liquid | Cologne 2016",
    "Autograph Capsule | Team Liquid | MLG Columbus 2016",
    "Autograph Capsule | Team SoloMid | Cluj-Napoca 2015",
    "Autograph Capsule | Team SoloMid | Cologne 2015",
    "Autograph Capsule | Team eBettle | Cologne 2015",
    "Autograph Capsule | Titan | Cluj-Napoca 2015",
    "Autograph Capsule | Titan | Cologne 2015",
    "Autograph Capsule | Vexed Gaming | Cluj-Napoca 2015",
    "Autograph Capsule | Virtus.Pro | Atlanta 2017",
    "Autograph Capsule | Virtus.Pro | Cluj-Napoca 2015",
    "Autograph Capsule | Virtus.Pro | Cologne 2015",
    "Autograph Capsule | Virtus.Pro | Cologne 2016",
    "Autograph Capsule | Virtus.Pro | MLG Columbus 2016",
    "Autograph Capsule | mousesports | Atlanta 2017",
    "Autograph Capsule | mousesports | Cluj-Napoca 2015",
    "Autograph Capsule | mousesports | Cologne 2015",
    "Autograph Capsule | mousesports | Cologne 2016",
    "Autograph Capsule | mousesports | MLG Columbus 2016",
    "B Squadron Officer | SAS",
    "Baggage Pin",
    "Battlefield 2042 Sticker Capsule",
    "Berlin 2019 Legends (Holo-Foil)",
    "Berlin 2019 Legends Autograph Capsule",
    "Berlin 2019 Minor Challengers (Holo-Foil)",
    "Berlin 2019 Minor Challengers Autograph Capsule",
    "Berlin 2019 Returning Challengers (Holo-Foil)",
    "Berlin 2019 Returning Challengers Autograph Capsule",
    "Berlin 2019 Viewer Pass",
    "Bestiary Capsule",
    "Bio-Haz Specialist | SWAT",
    "Black Mesa Pin",
    "Blackwolf | Sabre",
    "Bloodhound Pin",
    "Bloody Darryl The Strapped | The Professionals",
    "Boston 2018 Attending Legends (Holo-Foil)",
    "Boston 2018 Attending Legends Autograph Capsule",
    "Boston 2018 Legends (Holo-Foil)",
    "Boston 2018 Legends Autograph Capsule",
    "Boston 2018 Minor Challengers (Holo-Foil)",
    "Boston 2018 Minor Challengers Autograph Capsule",
    "Boston 2018 Minor Challengers with Flash Gaming (Holo-Foil)",
    "Boston 2018 Minor Challengers with Flash Gaming Autograph Capsule",
    "Boston 2018 Returning Challengers (Holo-Foil)",
    "Boston 2018 Returning Challengers Autograph Capsule",
    "Bravo Pin",
    "Brigadier General Pin",
    "Buckshot | NSWC SEAL",
    "Budapest 2025 Challengers Autograph Capsule",
    "Budapest 2025 Challengers Sticker Capsule",
    "Budapest 2025 Champions Autograph Capsule",
    "Budapest 2025 Contenders Autograph Capsule",
    "Budapest 2025 Contenders Sticker Capsule",
    "Budapest 2025 Legends Autograph Capsule",
    "Budapest 2025 Legends Sticker Capsule",
    "Budapest 2025 Viewer Pass",
    "CMB Pin",
    "CS20 Case",
    "CS20 Sticker Capsule",
    "CS:GO Patch Pack",
    "CS:GO Weapon Case",
    "CS:GO Weapon Case 2",
    "CS:GO Weapon Case 3",
    "Cache Pin",
    "Canals Pin",
    "Charm | 8 Ball IGL",
    "Charm | Baby Karat CT",
    "Charm | Baby Karat T",
    "Charm | Baby's AK",
    "Charm | Backsplash",
    "Charm | Big Brain",
    "Charm | Big Kev",
    "Charm | Biomech",
    "Charm | Bomb Tag",
    "Charm | Butane Buddy",
    "Charm | Chicken Lil'",
    "Charm | Dead Weight",
    "Charm | Diamond Dog",
    "Charm | Die-cast AK",
    "Charm | Diner Dog",
    "Charm | Disco MAC",
    "Charm | Dr. Brian",
    "Charm | Eye of Ball",
    "Charm | Flash Bomb",
    "Charm | Fluffy",
    "Charm | Glamour Shot",
    "Charm | Glitter Bomb",
    "Charm | Gritty",
    "Charm | Hang Loose",
    "Charm | Hot Hands",
    "Charm | Hot Howl",
    "Charm | Hot Sauce",
    "Charm | Hot Wurst",
    "Charm | Hungry Eyes",
    "Charm | Lil' Ava",
    "Charm | Lil' Baller",
    "Charm | Lil' Bloody",
    "Charm | Lil' Boo",
    "Charm | Lil' Buns",
    "Charm | Lil' Cackle",
    "Charm | Lil' Cap Gun",
    "Charm | Lil' Chirp",
    "Charm | Lil' Chomper",
    "Charm | Lil' Crass",
    "Charm | Lil' Curse",
    "Charm | Lil' Dumplin'",
    "Charm | Lil' Eco",
    "Charm | Lil' Eldritch",
    "Charm | Lil' Facelift",
    "Charm | Lil' Ferno",
    "Charm | Lil' Goop",
    "Charm | Lil' Happy",
    "Charm | Lil' Hero",
    "Charm | Lil' Moments",
    "Charm | Lil' Monster",
    "Charm | Lil' No. 2",
    "Charm | Lil' Prick",
    "Charm | Lil' SAS",
    "Charm | Lil' Sandy",
    "Charm | Lil' Serpent",
    "Charm | Lil' Smokey",
    "Charm | Lil' Squatch",
    "Charm | Lil' Squirt",
    "Charm | Lil' Teacup",
    "Charm | Lil' Tusk",
    "Charm | Lil' Vino",
    "Charm | Lil' Whiskers",
    "Charm | Lil' Yeti",
    "Charm | Lil' Zen",
    "Charm | Magmatude",
    "Charm | POP Art",
    "Charm | Pinch O' Salt",
    "Charm | Piñatita",
    "Charm | Pocket AWP",
    "Charm | Pocket Pop",
    "Charm | Quick Silver",
    "Charm | Semi-Precious",
    "Charm | Splatter Cat",
    "Charm | Stitch-Loaded",
    "Charm | That's Bananas",
    "Charm | Titeenium AWP",
    "Charm | Whittle Guy",
    "Charm | Whittle Knife",
    "Chef d'Escadron Rouchard | Gendarmerie Nationale",
    "Chem-Haz Capitaine | Gendarmerie Nationale",
    "Chem-Haz Specialist | SWAT",
    "Chicken Capsule",
    "Chroma 2 Case",
    "Chroma 3 Case",
    "Chroma Case",
    "Chroma Pin",
    "City 17 Pin",
    "Civil Protection Pin",
    "Clutch Case",
    "Cmdr. Davida 'Goggles' Fernandez | SEAL Frogman",
    "Cmdr. Frank 'Wet Sox' Baroud | SEAL Frogman",
    "Cmdr. Mae 'Dead Cold' Jamison | SWAT",
    "Cobblestone Pin",
    "Col. Mangos Dabisi | Guerrilla Warfare",
    "Collectible Pins Capsule Series 1",
    "Collectible Pins Capsule Series 2",
    "Collectible Pins Capsule Series 3",
    "Cologne 2016 Challengers (Holo-Foil)",
    "Cologne 2016 Legends (Holo-Foil)",
    "Combine Helmet Pin",
    "Community Capsule 2018",
    "Community Sticker Capsule 1",
    "Copenhagen 2024 Challengers Autograph Capsule",
    "Copenhagen 2024 Challengers Sticker Capsule",
    "Copenhagen 2024 Champions Autograph Capsule",
    "Copenhagen 2024 Contenders Autograph Capsule",
    "Copenhagen 2024 Contenders Sticker Capsule",
    "Copenhagen 2024 Legends Autograph Capsule",
    "Copenhagen 2024 Legends Sticker Capsule",
    "Copenhagen 2024 Viewer Pass",
    "Copper Lambda Pin",
    "Crasswater The Forgotten | Guerrilla Warfare",
    "D Squadron Officer | NZSAS",
    "Danger Zone Case",
    "Death Sentence Pin",
    "Deluge Music Kit Box",
    "Dragomir | Sabre",
    "Dragomir | Sabre Footsoldier",
    "DreamHack 2014 Legends (Holo-Foil)",
    "DreamHack Cluj-Napoca 2015 Challengers (Foil)",
    "DreamHack Cluj-Napoca 2015 Legends (Foil)",
    "Dreams & Nightmares Case",
    "Dust II Pin",
    "EMS Katowice 2014 Challengers",
    "EMS Katowice 2014 Legends",
    "ESL One Cologne 2014 Challengers",
    "ESL One Cologne 2014 Legends",
    "ESL One Cologne 2015 Challengers (Foil)",
    "ESL One Cologne 2015 Legends (Foil)",
    "ESL One Katowice 2015 Challengers (Holo-Foil)",
    "ESL One Katowice 2015 Legends (Holo-Foil)",
    "Easy Peasy Pin",
    "Elite Trapper Solman | Guerrilla Warfare",
    "Enforcer | Phoenix",
    "Enfu Sticker Capsule",
    "Espionage Sticker Capsule",
    "Falchion Case",
    "Feral Predators Capsule",
    "Fever Case",
    "Fracture Case",
    "Gallery Case",
    "Gamma 2 Case",
    "Gamma Case",
    "Getaway Sally | The Professionals",
    "Gift Package",
    "Glove Case",
    "Ground Rebel  | Elite Crew",
    "Guardian 2 Pin",
    "Guardian 3 Pin",
    "Guardian Elite Pin",
    "Guardian Pin",
    "Half-Life: Alyx Collectible Pins Capsule",
    "Half-Life: Alyx Patch Pack",
    "Half-Life: Alyx Sticker Capsule",
    "Halo Capsule",
    "Headcrab Glyph Pin",
    "Health Pin",
    "Horizon Case",
    "Howl Pin",
    "Huntsman Weapon Case",
    "Hydra Pin",
    "Inferno 2 Pin",
    "Inferno Pin",
    "Initiators Music Kit Box",
    "Italy Pin",
    "John 'Van Healen' Kask | SWAT",
    "Jungle Rebel | Elite Crew",
    "Katowice 2019 Legends (Holo-Foil)",
    "Katowice 2019 Legends Autograph Capsule",
    "Katowice 2019 Minor Challengers (Holo-Foil)",
    "Katowice 2019 Minor Challengers Autograph Capsule",
    "Katowice 2019 Returning Challengers (Holo-Foil)",
    "Katowice 2019 Returning Challengers Autograph Capsule",
    "Katowice 2019 Viewer Pass",
    "Kilowatt Case",
    "Krakow 2017 Challengers (Holo-Foil)",
    "Krakow 2017 Challengers Autograph Capsule",
    "Krakow 2017 Legends (Holo-Foil)",
    "Krakow 2017 Legends Autograph Capsule",
    "Lambda Pin",
    "Lieutenant 'Tree Hugger' Farlow | SWAT",
    "Lieutenant Rex Krikey | SEAL Frogman",
    "Little Kev | The Professionals",
    "London 2018 Legends (Holo-Foil)",
    "London 2018 Legends Autograph Capsule",
    "London 2018 Minor Challengers (Holo-Foil)",
    "London 2018 Minor Challengers Autograph Capsule",
    "London 2018 Returning Challengers (Holo-Foil)",
    "London 2018 Returning Challengers Autograph Capsule",
    "Lt. Commander Ricksaw | NSWC SEAL",
    "MLG Columbus 2016 Challengers (Holo-Foil)",
    "MLG Columbus 2016 Legends (Holo-Foil)",
    "Markus Delrow | FBI HRT",
    "Masterminds 2 Music Kit Box",
    "Masterminds Music Kit Box",
    "Maximus | Sabre",
    "Michael Syfers  | FBI Sniper",
    "Militia Pin",
    "Mirage Pin",
    "Music Kit | 3kliksphilip, Heading for the Source",
    "Music Kit | AWOLNATION, I Am",
    "Music Kit | Adam Beyer, Red Room",
    "Music Kit | Amon Tobin, All for Dust",
    "Music Kit | Austin Wintory, Bachram",
    "Music Kit | Austin Wintory, Desert Fire",
    "Music Kit | Austin Wintory, Mocha Petal",
    "Music Kit | Austin Wintory, The Devil Went Clubbing in Georgia",
    "Music Kit | Beartooth, Disgusting",
    "Music Kit | Ben Bromfield, Rabbit Hole",
    "Music Kit | Chipzel, ~Yellow Magic~",
    "Music Kit | DRYDEN, Feel The Power",
    "Music Kit | Damjan Mravunac, The Talos Principle",
    "Music Kit | Daniel Sadowski, Crimson Assault",
    "Music Kit | Daniel Sadowski, Dead Shot",
    "Music Kit | Daniel Sadowski, Eye of the Dragon",
    "Music Kit | Daniel Sadowski, The 8-Bit Kit",
    "Music Kit | Daniel Sadowski, Total Domination",
    "Music Kit | Darude, Moments CSGO",
    "Music Kit | Denzel Curry, ULTIMATE",
    "Music Kit | Dren McDonald, Coffee! Kofe! Kahveh!",
    "Music Kit | Dren, Death's Head Demolition",
    "Music Kit | Dren, Gunman Taco Truck",
    "Music Kit | Feed Me, High Noon",
    "Music Kit | Freaky DNA, Vici",
    "Music Kit | Ghost, Skeletá",
    "Music Kit | HEALTH, RAT WARS",
    "Music Kit | Humanity's Last Breath, Void",
    "Music Kit | ISOxo, inhuman",
    "Music Kit | Ian Hultquist, Lion's Mouth",
    "Music Kit | James and the Cold Gun, Chewing Glass",
    "Music Kit | Jesse Harlin, Astro Bellum",
    "Music Kit | Jonathan Young, Starship Velociraptor",
    "Music Kit | Juelz, Floorspace",
    "Music Kit | Juelz, Shooters",
    "Music Kit | KILL SCRIPT, All Night",
    "Music Kit | Kelly Bailey, Hazardous Environments",
    "Music Kit | Ki:Theory, MOLOTOV",
    "Music Kit | Killer Mike, MICHAEL",
    "Music Kit | Knock2, Make U SWEAT!",
    "Music Kit | Knock2, dashstar*",
    "Music Kit | Laura Shigihara: Work Hard, Play Hard",
    "Music Kit | Lennie Moore, Java Havana Funkaloo",
    "Music Kit | Mateo Messina, For No Mankind",
    "Music Kit | Matt Lange, IsoRhythm",
    "Music Kit | Matt Levine, Agency",
    "Music Kit | Matt Levine, Drifter",
    "Music Kit | Meechy Darko, Gothic Luxury",
    "Music Kit | Michael Bross, Invasion!",
    "Music Kit | Midnight Riders, All I Want for Christmas",
    "Music Kit | Mord Fustang, Diamonds",
    "Music Kit | Neck Deep, The Lowlife Pack",
    "Music Kit | New Beat Fund, Sponge Fingerz",
    "Music Kit | Noisia, Sharpened",
    "Music Kit | PVRIS, Evergreen",
    "Music Kit | Perfect World, Ay Hey",
    "Music Kit | Perfect World, 花脸 Hua Lian (Painted Face)",
    "Music Kit | Proxy, Battlepack",
    "Music Kit | Rad Cat, Reason",
    "Music Kit | Robert Allaire, Insurgency",
    "Music Kit | Sam Marshall, Bodacious",
    "Music Kit | Sam Marshall, Clutch",
    "Music Kit | Sarah Schachner, KOLIBRI",
    "Music Kit | Sasha, LNOE",
    "Music Kit | Scarlxrd, CHAIN$AW.LXADXUT.",
    "Music Kit | Scarlxrd: King, Scar",
    "Music Kit | Sean Murray, A*D*8",
    "Music Kit | Selective Response, No Love Only Pleasure",
    "Music Kit | Skog, II-Headshot",
    "Music Kit | Skog, Metal",
    "Music Kit | Sullivan King, Lock Me Up",
    "Music Kit | TWERL and Ekko & Sidetrack, Under Bright Lights",
    "Music Kit | The Verkkars & n0thing, Flashbang Dance",
    "Music Kit | The Verkkars, EZ4ENCE",
    "Music Kit | Tigercub, The Perfume of Decay",
    "Music Kit | Tim Huling, Devil's Paintbrush",
    "Music Kit | Tim Huling, Neo Noir",
    "Music Kit | Tree Adams and Ben Bromfield, M.U.D.D. FORCE",
    "Music Kit | Tree Adams, Seventh Moon",
    "Music Kit | Troels Folmann, Uber Blasto Phone",
    "Music Kit | Various Artists, Hotline Miami",
    "Music Kit | bbno$, u mad!",
    "NIGHTMODE Music Kit Box",
    "Nuke Pin",
    "Number K | The Professionals",
    "Office Pin",
    "Officer Jacques Beltram | Gendarmerie Nationale",
    "Operation Bloodhound Access Pass",
    "Operation Bravo Case",
    "Operation Bravo Pass",
    "Operation Breakout All Access Pass",
    "Operation Breakout Weapon Case",
    "Operation Broken Fang Case",
    "Operation Broken Fang Premium Pass",
    "Operation Hydra Access Pass",
    "Operation Hydra Case",
    "Operation Payback Pass",
    "Operation Phoenix Pass",
    "Operation Phoenix Weapon Case",
    "Operation Riptide Case",
    "Operation Riptide Premium Pass",
    "Operation Shattered Web Premium Pass",
    "Operation Vanguard Access Pass",
    "Operation Vanguard Weapon Case",
    "Operation Wildfire Access Pass",
    "Operation Wildfire Case",
    "Operator | FBI SWAT",
    "Osiris | Elite Crew",
    "Overpass Pin",
    "Pallet of Presents",
    "Paris 2023 Challengers Autograph Capsule",
    "Paris 2023 Challengers Sticker Capsule",
    "Paris 2023 Champions Autograph Capsule",
    "Paris 2023 Contenders Autograph Capsule",
    "Paris 2023 Contenders Sticker Capsule",
    "Paris 2023 Legends Autograph Capsule",
    "Paris 2023 Legends Sticker Capsule",
    "Paris 2023 Viewer Pass",
    "Perfect World Sticker Capsule 1",
    "Perfect World Sticker Capsule 2",
    "Phoenix Pin",
    "Pinups Capsule",
    "Poorly Drawn Capsule",
    "Primeiro Tenente | Brazilian 1st Battalion",
    "Prisma 2 Case",
    "Prisma Case",
    "Prof. Shahmat | Elite Crew",
    "Recoil Case",
    "Revolution Case",
    "Revolver Case",
    "Rezan The Ready | Sabre",
    "Rezan the Redshirt | Sabre",
    "Rio 2022 Challengers Autograph Capsule",
    "Rio 2022 Challengers Sticker Capsule",
    "Rio 2022 Champions Autograph Capsule",
    "Rio 2022 Contenders Autograph Capsule",
    "Rio 2022 Contenders Sticker Capsule",
    "Rio 2022 Legends Autograph Capsule",
    "Rio 2022 Legends Sticker Capsule",
    "Rio 2022 Viewer Pass",
    "Safecracker Voltzmann | The Professionals",
    "Seal Team 6 Soldier | NSWC SEAL",
    "Sealed Dead Hand Terminal",
    "Sealed Genesis Terminal",
    "Sergeant Bombson | SWAT",
    "Shadow Case",
    "Shanghai 2024 Challengers Autograph Capsule",
    "Shanghai 2024 Challengers Sticker Capsule",
    "Shanghai 2024 Champions Autograph Capsule",
    "Shanghai 2024 Contenders Autograph Capsule",
    "Shanghai 2024 Contenders Sticker Capsule",
    "Shanghai 2024 Legends Autograph Capsule",
    "Shanghai 2024 Legends Sticker Capsule",
    "Shanghai 2024 Viewer Pass",
    "Shattered Web Case",
    "Sir Bloody Darryl Royale | The Professionals",
    "Sir Bloody Loudmouth Darryl | The Professionals",
    "Sir Bloody Miami Darryl | The Professionals",
    "Sir Bloody Silent Darryl | The Professionals",
    "Sir Bloody Skullhead Darryl | The Professionals",
    "Skill Groups Capsule",
    "Slid3 Capsule",
    "Slingshot | Phoenix",
    "Snakebite Case",
    "Soldier | Phoenix",
    "Sous-Lieutenant Medic | Gendarmerie Nationale",
    "Special Agent Ava | FBI",
    "Spectrum 2 Case",
    "Spectrum Case",
    "Sticker Capsule",
    "Sticker Capsule 2",
    "Stockholm 2021 Challengers Patch Pack",
    "Stockholm 2021 Challengers Sticker Capsule",
    "Stockholm 2021 Champions Autograph Capsule",
    "Stockholm 2021 Contenders Patch Pack",
    "Stockholm 2021 Contenders Sticker Capsule",
    "Stockholm 2021 Finalists Autograph Capsule",
    "Stockholm 2021 Legends Patch Pack",
    "Stockholm 2021 Legends Sticker Capsule",
    "Stockholm 2021 Viewer Pass",
    "Street Soldier | Phoenix",
    "Sugarface Capsule",
    "Sustenance! Pin",
    "Tacticians Music Kit Box",
    "Tactics Pin",
    "Team Roles Capsule",
    "The Boardroom Sticker Capsule",
    "The Elite Mr. Muhlik | Elite Crew",
    "Train Pin",
    "Trapper Aggressor | Guerrilla Warfare",
    "Trapper | Guerrilla Warfare",
    "Valeria Phoenix Pin",
    "Victory Pin",
    "Vortigaunt Pin",
    "Vypa Sista of the Revolution | Guerrilla Warfare",
    "Warhammer 40,000 Adeptus Astartes Sticker Capsule",
    "Warhammer 40,000 Imperium Sticker Capsule",
    "Warhammer 40,000 Sticker Capsule",
    "Warhammer 40,000 Traitor Astartes Sticker Capsule",
    "Warhammer 40,000 Xenos Sticker Capsule",
    "Welcome to the Clutch Pin",
    "Wildfire Pin",
    "Winter Offensive Weapon Case",
    "X-Ray P250 Package",
    "eSports 2013 Case",
    "eSports 2013 Winter Case",
    "eSports 2014 Summer Case",
]
