# count = 135  (pred_cv > 0.075)

ITEMS = [
    "MP9 | Airlock (Field-Tested)",
    "Galil AR | Rainbow Spoon (Minimal Wear)",
    "M4A1-S | Guardian (Field-Tested)",
    "AK-47 | Nouveau Rouge (Minimal Wear)",
    "Desert Eagle | Printstream (Field-Tested)",
    "AK-47 | Neon Rider (Field-Tested)",
    "Desert Eagle | Midnight Storm (Minimal Wear)",
    "AK-47 | Elite Build (Minimal Wear)",
    "Five-SeveN | Case Hardened (Battle-Scarred)",
    "Desert Eagle | Printstream (Minimal Wear)",
    "USP-S | Black Lotus (Minimal Wear)",
    "Glock-18 | Steel Disruption (Factory New)",
    "USP-S | The Traitor (Battle-Scarred)",
    "Glock-18 | Water Elemental (Minimal Wear)",
    "Tec-9 | Fuel Injector (Field-Tested)",
    "AWP | Exoskeleton (Field-Tested)",
    "USP-S | Jawbreaker (Minimal Wear)",
    "Glock-18 | Gold Toof (Minimal Wear)",
    "AWP | Sun in Leo (Field-Tested)",
    "AK-47 | Asiimov (Field-Tested)",
    "M4A4 | Tooth Fairy (Field-Tested)",
    "Desert Eagle | Kumicho Dragon (Minimal Wear)",
    "M4A4 | Full Throttle (Battle-Scarred)",
    "Glock-18 | Vogue (Field-Tested)",
    "P2000 | Imperial Dragon (Battle-Scarred)",
    "M4A4 | Polysoup (Field-Tested)",
    "Desert Eagle | Code Red (Minimal Wear)",
    "USP-S | Whiteout (Field-Tested)",
    "USP-S | Kill Confirmed (Field-Tested)",
    "AK-47 | The Oligarch (Battle-Scarred)",
    "MP9 | Hydra (Minimal Wear)",
    "Five-SeveN | Heat Treated (Battle-Scarred)",
    "M4A1-S | Nightmare (Field-Tested)",
    "Sawed-Off | Wasteland Princess (Minimal Wear)",
    "Desert Eagle | Mulberry (Minimal Wear)",
    "Five-SeveN | Monkey Business (Minimal Wear)",
    "MP9 | Food Chain (Field-Tested)",
    "Glock-18 | Gold Toof (Field-Tested)",
    "USP-S | Black Lotus (Factory New)",
    "AWP | Atheris (Field-Tested)",
    "G3SG1 | Stinger (Field-Tested)",
    "M4A1-S | Black Lotus (Minimal Wear)",
    "SSG 08 | Big Iron (Minimal Wear)",
    "AUG | Fleet Flock (Minimal Wear)",
    "P90 | Shallow Grave (Minimal Wear)",
    "M4A4 | Neo-Noir (Field-Tested)",
    "AK-47 | Redline (Battle-Scarred)",
    "AUG | Syd Mead (Minimal Wear)",
    "AK-47 | Nightwish (Battle-Scarred)",
    "Desert Eagle | Crimson Web (Field-Tested)",
    "Dual Berettas | Royal Consorts (Field-Tested)",
    "M4A4 | The Emperor (Field-Tested)",
    "Nova | Sobek's Bite (Field-Tested)",
    "M4A4 | Temukau (Field-Tested)",
    "M4A4 | Desolate Space (Battle-Scarred)",
    "Glock-18 | Mirror Mosaic (Battle-Scarred)",
    "MP9 | Hydra (Field-Tested)",
    "AK-47 | Cartel (Minimal Wear)",
    "AK-47 | Cartel (Factory New)",
    "USP-S | Monster Mashup (Field-Tested)",
    "P2000 | Urban Hazard (Factory New)",
    "AK-47 | Frontside Misty (Minimal Wear)",
    "Desert Eagle | Crimson Web (Minimal Wear)",
    "Desert Eagle | Calligraffiti (Factory New)",
    "M4A4 | Tooth Fairy (Minimal Wear)",
    "SSG 08 | Ghost Crusader (Factory New)",
    "UMP-45 | Wild Child (Battle-Scarred)",
    "USP-S | Printstream (Minimal Wear)",
    "M4A1-S | Control Panel (Field-Tested)",
    "P250 | Epicenter (Field-Tested)",
    "MP7 | Fade (Factory New)",
    "Sawed-Off | Devourer (Field-Tested)",
    "AK-47 | Slate (Battle-Scarred)",
    "AK-47 | Head Shot (Field-Tested)",
    "UMP-45 | Neo-Noir (Field-Tested)",
    "AK-47 | Ice Coaled (Field-Tested)",
    "Galil AR | Black Sand (Factory New)",
    "P90 | Nostalgia (Minimal Wear)",
    "AWP | Redline (Field-Tested)",
    "Five-SeveN | Boost Protocol (Factory New)",
    "AK-47 | Blue Laminate (Minimal Wear)",
    "AK-47 | Aphrodite (Minimal Wear)",
    "AK-47 | Nouveau Rouge (Battle-Scarred)",
    "M4A4 | Hellish (Battle-Scarred)",
    "AK-47 | Head Shot (Battle-Scarred)",
    "AWP | Exoskeleton (Battle-Scarred)",
    "AK-47 | Slate (Minimal Wear)",
    "Five-SeveN | Case Hardened (Minimal Wear)",
    "Desert Eagle | Urban DDPAT (Minimal Wear)",
    "AWP | Ice Coaled (Factory New)",
    "AUG | Momentum (Field-Tested)",
    "AWP | Elite Build (Battle-Scarred)",
    "AUG | Fleet Flock (Battle-Scarred)",
    "Galil AR | Rainbow Spoon (Factory New)",
    "MP7 | Powercore (Minimal Wear)",
    "Glock-18 | Vogue (Minimal Wear)",
    "AWP | Atheris (Minimal Wear)",
    "P90 | Storm (Minimal Wear)",
    "USP-S | Guardian (Minimal Wear)",
    "SSG 08 | Bloodshot (Field-Tested)",
    "SCAR-20 | Wild Berry (Factory New)",
    "Glock-18 | Nuclear Garden (Factory New)",
    "P250 | Visions (Minimal Wear)",
    "Five-SeveN | Heat Treated (Minimal Wear)",
    "M4A4 | Polysoup (Factory New)",
    "G3SG1 | Dream Glade (Factory New)",
    "CZ75-Auto | Red Astor (Factory New)",
    "FAMAS | Mecha Industries (Factory New)",
    "Nova | Antique (Factory New)",
    "SSG 08 | Detour (Factory New)",
    "AWP | Hyper Beast (Battle-Scarred)",
    "XM1014 | Entombed (Minimal Wear)",
    "SCAR-20 | Bloodsport (Factory New)",
    "UMP-45 | Crimson Foil (Factory New)",
    "AWP | Ice Coaled (Battle-Scarred)",
    "FAMAS | Yeti Camo (Factory New)",
    "XM1014 | Halftone Shift (Factory New)",
    "XM1014 | Ziggy (Factory New)",
    "CZ75-Auto | Slalom (Factory New)",
    "Desert Eagle | Printstream (Factory New)",
    "MP9 | Arctic Tri-Tone (Factory New)",
    "Galil AR | Eco (Field-Tested)",
    "SG 553 | Dragon Tech (Factory New)",
    "XM1014 | Entombed (Factory New)",
    "USP-S | Alpine Camo (Factory New)",
    "Glock-18 | Block-18 (Factory New)",
    "M4A4 | Evil Daimyo (Field-Tested)",
    "Negev | dev_texture (Factory New)",
    "Desert Eagle | Night (Minimal Wear)",
    "AK-47 | Redline (Field-Tested)",
    "AK-47 | Slate (Well-Worn)",
    "AK-47 | Emerald Pinstripe (Field-Tested)",
    "AWP | Asiimov (Battle-Scarred)",
    "M4A1-S | Basilisk (Minimal Wear)",
    "Glock-18 | Water Elemental (Battle-Scarred)",
]
