ITEMS = [
    "Music Kit | Selective Response, No Love Only Pleasure",
    "Sealed Dead Hand Terminal",
    "Glock-18 | Catacombs (Field-Tested)",
    "Glock-18 | Catacombs (Minimal Wear)",
    "Charm | Die-cast AK",
    "London 2018 Returning Challengers Autograph Capsule",
    "Horizon Case",
    "AWP | Pit Viper (Well-Worn)",
    "Autograph Capsule | Fnatic | Cluj-Napoca 2015",
    "Music Kit | Scarlxrd: King, Scar",
    "Stockholm 2021 Champions Autograph Capsule",
    "Music Kit | Ben Bromfield, Rabbit Hole",
    "Music Kit | Matt Lange, IsoRhythm",
    "Danger Zone Case",
    "Autograph Capsule | Group A (Foil) | Cologne 2015",
    "AK-47 | Elite Build (Well-Worn)",
    "Prisma Case",
    "Music Kit | Matt Levine, Drifter",
    "Shadow Case",
    "CS20 Case",
    "Desert Eagle | Light Rail (Minimal Wear)",
    "Gamma 2 Case",
    "AK-47 | Slate (Minimal Wear)",
    "Gamma Case",
    "Glock-18 | Bunsen Burner (Minimal Wear)",
    "Spectrum Case",
    "Charm | Magmatude",
    "Music Kit | Darude, Moments CSGO",
    "Music Kit | Adam Beyer, Red Room",
    "Seal Team 6 Soldier | NSWC SEAL",
    "Music Kit | The Verkkars & n0thing, Flashbang Dance",
    "Charm | Lil' Happy",
    "Prisma 2 Case",
    "Music Kit | Ghost, Skeletá",
    "M4A1-S | Emphorosaur-S (Minimal Wear)",
    "Music Kit | bbno$, u mad!",
    "Clutch Case",
    "CMB Pin",
    "AK-47 | Uncharted (Well-Worn)",
    "Charm | Pocket Pop",
    "Operation Phoenix Weapon Case",
    "Sustenance! Pin",
    "Berlin 2019 Legends Autograph Capsule",
    "Victory Pin",
    "AWP | Pit Viper (Battle-Scarred)",
    "Office Pin",
    "AK-47 | Elite Build (Minimal Wear)",
    "Chroma Case",
    "Falchion Case",
    "Autograph Capsule | Renegades | Cologne 2015",
    "Chroma 3 Case",
    "Spectrum 2 Case",
    "Charm | Lil' Goop",
    "Boston 2018 Returning Challengers Autograph Capsule",
    "Music Kit | Rad Cat, Reason",
    "Charm | Lil' Bloody",
    "Charm | Lil' Buns",
    "AK-47 | Ice Coaled (Well-Worn)",
    "Gallery Case",
    "Dreams & Nightmares Case",
    "AK-47 | Elite Build (Field-Tested)",
    "Music Kit | Juelz, Floorspace",
    "AWP | PAW (Well-Worn)",
    "AWP | Fever Dream (Minimal Wear)",
    "Guardian 3 Pin",
    "AWP | Worm God (Minimal Wear)",
    "Autograph Capsule | Team EnVyUs | Cologne 2015",
    "Music Kit | Feed Me, High Noon",
    "Charm | Quick Silver",
    "Glock-18 | Ironwork (Minimal Wear)",
    "Desert Eagle | Trigger Discipline (Minimal Wear)",
    "CZ75-Auto | Eco (Field-Tested)",
    "AWP | Sun in Leo (Minimal Wear)",
    "Music Kit | Perfect World, Ay Hey",
    "Stockholm 2021 Challengers Patch Pack",
    "Bravo Pin",
    "Autograph Capsule | Team EnVyUs | Cluj-Napoca 2015",
    "MP7 | Cirrus (Field-Tested)",
    "AWP | Pit Viper (Field-Tested)",
    "Death Sentence Pin",
    "Music Kit | Matt Levine, Agency",
    "The Elite Mr. Muhlik | Elite Crew",
    "Autograph Capsule | Virtus.Pro | Cologne 2015",
    "Guardian 2 Pin",
    "Headcrab Glyph Pin",
    "Music Kit | Ki:Theory, MOLOTOV",
    "City 17 Pin",
    "3rd Commando Company | KSK",
    "Music Kit | Meechy Darko, Gothic Luxury",
    "AWP | Mortis (Well-Worn)",
    "Operation Breakout Weapon Case",
    "Shattered Web Case",
    "AWP | POP AWP (Minimal Wear)",
    "Combine Helmet Pin",
    "Warhammer 40,000 Traitor Astartes Sticker Capsule",
    "Cobblestone Pin",
    "Canals Pin",
    "AK-47 | Elite Build (Battle-Scarred)",
    "Italy Pin",
    "Operation Vanguard Weapon Case",
    "Revolver Case",
    "Music Kit | Freaky DNA, Vici",
    "Autograph Capsule | Fnatic | Cologne 2015",
    "Music Kit | Lennie Moore, Java Havana Funkaloo",
    "Music Kit | Ian Hultquist, Lion's Mouth",
    "Music Kit | HEALTH, RAT WARS",
    "Welcome to the Clutch Pin",
    "Aces High Pin",
    "M4A4 | Tooth Fairy (Well-Worn)",
    "AWP | Capillary (Well-Worn)",
    "Autograph Capsule | Team SoloMid | Cologne 2015",
    "Operation Riptide Case",
    "Operation Wildfire Case",
    "AK-47 | Uncharted (Minimal Wear)",
    "Glock-18 | Vogue (Well-Worn)",
    "Berlin 2019 Returning Challengers (Holo-Foil)",
    "Music Kit | TWERL and Ekko & Sidetrack, Under Bright Lights",
    "Phoenix Pin",
    "London 2018 Minor Challengers (Holo-Foil)",
    "Berlin 2019 Returning Challengers Autograph Capsule",
    "Community Sticker Capsule 1",
    "Music Kit | Sam Marshall, Clutch",
    "Operation Broken Fang Case",
    "London 2018 Legends Autograph Capsule",
    "AWP | Worm God (Field-Tested)",
    "Anubis Collection Package",
    "AK-47 | Crossfade (Minimal Wear)",
    "Enforcer | Phoenix",
    "Music Kit | PVRIS, Evergreen",
    "AK-47 | Blue Laminate (Field-Tested)",
    "MP7 | Cirrus (Minimal Wear)",
    "Music Kit | Denzel Curry, ULTIMATE",
    "Rezan the Redshirt | Sabre",
    "M4A4 | Magnesium (Minimal Wear)",
    "Markus Delrow | FBI HRT",
    "MP7 | Bloodsport (Field-Tested)",
    "Baggage Pin",
    "Vortigaunt Pin",
    "Music Kit | DRYDEN, Feel The Power",
    "Music Kit | 3kliksphilip, Heading for the Source",
    "AWP | Duality (Well-Worn)",
    "Chroma Pin",
    "M4A4 | Converter (Minimal Wear)",
    "M4A1-S | Night Terror (Minimal Wear)",
    "NIGHTMODE Music Kit Box",
    "Tactics Pin",
    "Glock-18 | Moonrise (Field-Tested)",
    "Music Kit | Knock2, Make U SWEAT!",
    "Autograph Capsule | Legends (Foil) | Cluj-Napoca 2015",
    "AK-47 | Aquamarine Revenge (Well-Worn)",
    "AWP | PAW (Field-Tested)",
    "AK-47 | Emerald Pinstripe (Well-Worn)",
    "Glock-18 | Umbral Rabbit (Minimal Wear)",
    "M4A1-S | Briefing (Minimal Wear)",
    "Slingshot | Phoenix",
    "Autograph Capsule | Natus Vincere | Cluj-Napoca 2015",
    "Black Mesa Pin",
    "Operator | FBI SWAT",
    "Music Kit | Mord Fustang, Diamonds",
    "Music Kit | KILL SCRIPT, All Night",
    "Music Kit | Midnight Riders, All I Want for Christmas",
    "AWP | Worm God (Well-Worn)",
    "Hydra Pin",
    "Berlin 2019 Minor Challengers Autograph Capsule",
    "CS:GO Weapon Case 3",
    "Music Kit | Knock2, dashstar*",
    "Poorly Drawn Capsule",
    "Civil Protection Pin",
    "AWP | Fever Dream (Battle-Scarred)",
    "M4A4 | Spider Lily (Minimal Wear)",
    "CZ75-Auto | Tacticat (Field-Tested)",
    "AK-47 | Cartel (Minimal Wear)",
    "Music Kit | The Verkkars, EZ4ENCE",
    "Charm | Hungry Eyes",
    "Easy Peasy Pin",
    "Train Pin",
    "Buckshot | NSWC SEAL",
    "Autograph Capsule | Group B (Foil) | Cologne 2015",
    "AWP | PAW (Minimal Wear)",
    "Charm | Lil' Whiskers",
    "Militia Pin",
    "Stockholm 2021 Contenders Sticker Capsule",
    "Inferno 2 Pin",
    "Music Kit | Daniel Sadowski, The 8-Bit Kit",
    "Desert Eagle | Corinthian (Factory New)",
    "AK-47 | Slate (Well-Worn)",
    "AK-47 | Crossfade (Field-Tested)",
    "AK-47 | Ice Coaled (Field-Tested)",
    "Maximus | Sabre",
    "AWP | Phobos (Minimal Wear)",
    "1st Lieutenant Farlow | SWAT",
    "CS:GO Weapon Case 2",
    "Autograph Capsule | Ninjas in Pyjamas | Cologne 2015",
    "Autograph Capsule | Virtus.Pro | Cluj-Napoca 2015",
    "Katowice 2019 Minor Challengers (Holo-Foil)",
    "M4A4 | Desolate Space (Minimal Wear)",
    "Nuke Pin",
    "B Squadron Officer | SAS",
    "Chroma 2 Case",
    "M4A1-S | Nightmare (Minimal Wear)",
    "Glock-18 | Weasel (Minimal Wear)",
    "AWP | Phobos (Field-Tested)",
    "Charm | Glamour Shot",
    "Berlin 2019 Minor Challengers (Holo-Foil)",
    "Glock-18 | Water Elemental (Well-Worn)",
    "AWP | Black Nile (Minimal Wear)",
    "Five-SeveN | Withered Vine (Minimal Wear)",
    "M4A4 | Neo-Noir (Well-Worn)",
    "Guardian Pin",
    "Osiris | Elite Crew",
    "Alyx Pin",
    "M4A4 | Tooth Fairy (Battle-Scarred)",
    "Music Kit | Tim Huling, Devil's Paintbrush",
    "Guardian Elite Pin",
    "Music Kit | Jonathan Young, Starship Velociraptor",
    "M4A4 | Converter (Field-Tested)",
    "Five-SeveN | Withered Vine (Field-Tested)",
    "AK-47 | Phantom Disruptor (Minimal Wear)",
    "Music Kit | Sam Marshall, Bodacious",
    "Music Kit | Scarlxrd, CHAIN$AW.LXADXUT.",
    "'Medium Rare' Crasswater | Guerrilla Warfare",
    "Charm | Glitter Bomb",
    "Cache Pin",
    "Copper Lambda Pin",
    "Prof. Shahmat | Elite Crew",
    "AK-47 | Legion of Anubis (Field-Tested)",
    "M4A4 | Evil Daimyo (Minimal Wear)",
    "'Two Times' McCoy | USAF TACP",
    "Music Kit | Robert Allaire, Insurgency",
    "Music Kit | Sarah Schachner, KOLIBRI",
    "Music Kit | Juelz, Shooters",
    "Music Kit | ISOxo, inhuman",
    "Music Kit | Austin Wintory, Mocha Petal",
    "AK-47 | Rat Rod (Field-Tested)",
    "Berlin 2019 Legends (Holo-Foil)",
    "Music Kit | Various Artists, Hotline Miami",
    "Charm | Lil' Moments",
    "AK-47 | Steel Delta (Minimal Wear)",
    "Winter Offensive Weapon Case",
    "Masterminds Music Kit Box",
    "AK-47 | Slate (Battle-Scarred)",
    "AWP | Atheris (Well-Worn)",
    "Dust II Pin",
    "AWP | Mortis (Battle-Scarred)",
    "Boston 2018 Minor Challengers with Flash Gaming Autograph Capsule",
    "Music Kit | Austin Wintory, Bachram",
    "Bloodhound Pin",
    "M4A1-S | Decimator (Field-Tested)",
    "Operation Hydra Case",
    "Charm | That's Bananas",
    "Music Kit | Daniel Sadowski, Eye of the Dragon",
    "AK-47 | Head Shot (Well-Worn)",
    "Glock-18 | Vogue (Factory New)",
    "Sergeant Bombson | SWAT",
    "Glock-18 | Weasel (Well-Worn)",
    "AK-47 | Rat Rod (Well-Worn)",
    "AK-47 | Blue Laminate (Minimal Wear)",
    "Music Kit | Austin Wintory, Desert Fire",
    "AK-47 | Phantom Disruptor (Field-Tested)",
    "AK-47 | Frontside Misty (Minimal Wear)",
    "Stockholm 2021 Challengers Sticker Capsule",
    "M4A4 | Evil Daimyo (Field-Tested)",
    "M4A4 | Global Offensive (Field-Tested)",
    "AWP | Chromatic Aberration (Field-Tested)",
    "Special Agent Ava | FBI",
    "AWP | Redline (Field-Tested)",
    "'The Doctor' Romanov | Sabre",
    "Health Pin",
    "Glock-18 | Moonrise (Well-Worn)",
    "Music Kit | Perfect World, 花脸 Hua Lian (Painted Face)",
    "Music Kit | Amon Tobin, All for Dust",
    "Music Kit | Laura Shigihara: Work Hard, Play Hard",
    "Music Kit | Tree Adams, Seventh Moon",
    "Music Kit | Chipzel, ~Yellow Magic~",
    "Music Kit | Dren McDonald, Coffee! Kofe! Kahveh!",
    "M4A4 | Converter (Well-Worn)",
    "Music Kit | Michael Bross, Invasion!",
    "Charm | Flash Bomb",
    "Charm | Diamond Dog",
    "Half-Life: Alyx Patch Pack",
    "Katowice 2019 Minor Challengers Autograph Capsule",
    "Charm | Lil' Ferno",
    "Music Kit | Sasha, LNOE",
    "Charm | Lil' Prick",
    "Autograph Capsule | Natus Vincere | Cologne 2015",
    "Autograph Capsule | Astralis | MLG Columbus 2016",
    "Charm | Lil' Monster",
]