# Auto-generated from preprocess screener
# INPUT_CSV = 'C:\\Roman\\cs-arbitrage\\skins_roundtrip_v1\\skin_homog\\screener_preprocess\\preprocess_metrics.csv'
# BASE_MIN = 3.0
# BASE_MAX = 500.0
# N_LISTINGS_MIN = 15
# REQUIRE_CAP_HIT = False
# AVG_DISCOUNT_MIN = -0.05
# AVG_DISCOUNT_MAX = None
# MEDIAN_DISCOUNT_MIN = None
# DISCOUNT_SAMPLE_N_MIN = 3
# N_OUTPUT_ITEMS = 1638

ITEMS = [
    "P90 | Ancient Earth (Factory New)",
    "Dual Berettas | Switch Board (Factory New)",
    "P90 | Traction (Factory New)",
    "MAC-10 | Whitefish (Factory New)",
    "Tec-9 | Phoenix Chalk (Factory New)",
    "Dual Berettas | Oil Change (Factory New)",
    "P250 | Dark Filigree (Factory New)",
    "Desert Eagle | Calligraffiti (Factory New)",
    "R8 Revolver | Tango (Factory New)",
    "AUG | Triqua (Factory New)",
    "MP7 | Sunbaked (Factory New)",
    "P250 | Cyber Shell (Factory New)",
    "SG 553 | Damascus Steel (Factory New)",
    "Galil AR | Black Sand (Factory New)",
    "MAG-7 | Popdog (Factory New)",
    "XM1014 | Solitude (Factory New)",
    "Desert Eagle | Mudder (Factory New)",
    "Desert Eagle | The Bronze (Factory New)",
    "Dual Berettas | Heist (Factory New)",
    "AUG | Amber Fade (Factory New)",
    "Desert Eagle | Blue Ply (Factory New)",
    "MP7 | Astrolabe (Factory New)",
    "Five-SeveN | Scumbria (Factory New)",
    "MP9 | Black Sand (Factory New)",
    "FAMAS | Faulty Wiring (Factory New)",
    "FAMAS | CaliCamo (Factory New)",
    "Tec-9 | Groundwater (Factory New)",
    "USP-S | Desert Tactical (Factory New)",
    "Tec-9 | Cracked Opal (Factory New)",
    "AK-47 | Emerald Pinstripe (Factory New)",
    "Glock-18 | Gamma Doppler (Factory New)",
    "P2000 | Urban Hazard (Factory New)",
    "Galil AR | Akoben (Factory New)",
    "MAC-10 | Strats (Factory New)",
    "AUG | Surveillance (Factory New)",
    "CZ75-Auto | Silver (Factory New)",
    "Tec-9 | Safety Net (Factory New)",
    "MAC-10 | Classic Crate (Factory New)",
    "FAMAS | Crypsis (Factory New)",
    "PP-Bizon | Photic Zone (Factory New)",
    "AUG | Carved Jade (Factory New)",
    "SSG 08 | Ghost Crusader (Factory New)",
    "SSG 08 | Hand Brake (Factory New)",
    "P90 | Off World (Factory New)",
    "P250 | Verdigris (Factory New)",
    "Glock-18 | Wraiths (Factory New)",
    "Dual Berettas | Moon in Libra (Factory New)",
    "Dual Berettas | Panther (Factory New)",
    "AWP | Acheron (Factory New)",
    "CZ75-Auto | Imprint (Factory New)",
    "Sawed-Off | Clay Ambush (Factory New)",
    "Glock-18 | Oxide Blaze (Factory New)",
    "XM1014 | Blue Tire (Factory New)",
    "Dual Berettas | Dualing Dragons (Factory New)",
    "FAMAS | Night Borre (Factory New)",
    "Galil AR | Sage Spray (Factory New)",
    "R8 Revolver | Survivalist (Factory New)",
    "FAMAS | Cyanospatter (Factory New)",
    "UMP-45 | Primal Saber (Field-Tested)",
    "Dual Berettas | Elite 1.6 (Factory New)",
    "Tec-9 | Brother (Factory New)",
    "MAG-7 | Navy Sheen (Factory New)",
    "XM1014 | Solitude (Minimal Wear)",
    "AUG | Luxe Trim (Factory New)",
    "Sawed-Off | Snake Camo (Factory New)",
    "MP7 | Tall Grass (Factory New)",
    "Tec-9 | Flash Out (Factory New)",
    "UMP-45 | Wild Child (Field-Tested)",
    "AUG | Radiation Hazard (Factory New)",
    "AWP | Safari Mesh (Factory New)",
    "Glock-18 | Warhawk (Factory New)",
    "AUG | Syd Mead (Field-Tested)",
    "AK-47 | Nightwish (Battle-Scarred)",
    "FAMAS | Hexane (Factory New)",
    "Five-SeveN | Forest Night (Factory New)",
    "M4A1-S | Player Two (Field-Tested)",
    "XM1014 | Entombed (Minimal Wear)",
    "MP7 | Powercore (Factory New)",
    "MP7 | Akoben (Factory New)",
    "Glock-18 | Ironwork (Factory New)",
    "AK-47 | Head Shot (Field-Tested)",
    "P250 | Hive (Factory New)",
    "FAMAS | Macabre (Factory New)",
    "MAC-10 | Sienna Damask (Factory New)",
    "Glock-18 | Bunsen Burner (Factory New)",
    "Glock-18 | Night (Minimal Wear)",
    "PP-Bizon | Bamboo Print (Factory New)",
    "P250 | Valence (Factory New)",
    "R8 Revolver | Desert Brush (Factory New)",
    "MAC-10 | Pipe Down (Factory New)",
    "PP-Bizon | Seabird (Factory New)",
    "USP-S | Pathfinder (Factory New)",
    "P90 | Desert DDPAT (Factory New)",
    "Desert Eagle | Night Heist (Factory New)",
    "Glock-18 | Clear Polymer (Factory New)",
    "AK-47 | Midnight Laminate (Field-Tested)",
    "Dual Berettas | Briar (Factory New)",
    "P2000 | Red FragCam (Factory New)",
    "Glock-18 | Red Tire (Factory New)",
    "Galil AR | Blue Titanium (Factory New)",
    "M4A1-S | Mud-Spec (Factory New)",
    "AK-47 | Uncharted (Factory New)",
    "Dual Berettas | Royal Consorts (Factory New)",
    "USP-S | Purple DDPAT (Factory New)",
    "Glock-18 | Catacombs (Factory New)",
    "Dual Berettas | Cartel (Factory New)",
    "StatTrak™ Zeus x27 | Olympus (Minimal Wear)",
    "Glock-18 | Weasel (Factory New)",
    "Tec-9 | Ossified (Factory New)",
    "Five-SeveN | Violent Daimyo (Factory New)",
    "Desert Eagle | Heat Treated (Factory New)",
    "FAMAS | Decommissioned (Factory New)",
    "AWP | Duality (Field-Tested)",
    "MAC-10 | Surfwood (Factory New)",
    "Dual Berettas | Balance (Factory New)",
    "MP9 | Slide (Factory New)",
    "Glock-18 | Grinder (Factory New)",
    "XM1014 | Entombed (Field-Tested)",
    "StatTrak™ XM1014 | Entombed (Field-Tested)",
    "AUG | Navy Murano (Factory New)",
    "AK-47 | Steel Delta (Factory New)",
    "Galil AR | Sandstorm (Minimal Wear)",
    "AUG | Aristocrat (Factory New)",
    "M4A1-S | Blood Tiger (Factory New)",
    "Glock-18 | Franklin (Factory New)",
    "AUG | Amber Slipstream (Factory New)",
    "AUG | Arctic Wolf (Factory New)",
    "P2000 | Wicked Sick (Field-Tested)",
    "UMP-45 | Primal Saber (Minimal Wear)",
    "AWP | Black Nile (Factory New)",
    "StatTrak™ XM1014 | Entombed (Minimal Wear)",
    "FAMAS | 2A2F (Factory New)",
    "P90 | Asiimov (Field-Tested)",
    "Dual Berettas | Anodized Navy (Factory New)",
    "Glock-18 | Off World (Factory New)",
    "Five-SeveN | Monkey Business (Field-Tested)",
    "P2000 | Imperial Dragon (Field-Tested)",
    "Glock-18 | Winterized (Factory New)",
    "M4A4 | The Emperor (Field-Tested)",
    "P2000 | Granite Marbleized (Factory New)",
    "MAC-10 | Lapis Gator (Factory New)",
    "AK-47 | Safari Mesh (Factory New)",
    "Five-SeveN | Nightshade (Factory New)",
    "AK-47 | Safety Net (Factory New)",
    "Negev | dev_texture (Factory New)",
    "Tec-9 | Mummy's Rot (Factory New)",
    "AWP | POP AWP (Factory New)",
    "M4A1-S | Fizzy POP (Factory New)",
    "StatTrak™ Dual Berettas | Melondrama (Field-Tested)",
    "Tec-9 | Snek-9 (Factory New)",
    "Five-SeveN | Fraise Crane (Factory New)",
    "R8 Revolver | Phoenix Marker (Factory New)",
    "Five-SeveN | Buddy (Factory New)",
    "PP-Bizon | Chemical Green (Factory New)",
    "AWP | Hyper Beast (Battle-Scarred)",
    "UMP-45 | Moonrise (Factory New)",
    "USP-S | Flashback (Factory New)",
    "P250 | Mint Kimono (Minimal Wear)",
    "P250 | Vino Primo (Factory New)",
    "UMP-45 | Momentum (Field-Tested)",
    "Desert Eagle | Midnight Storm (Factory New)",
    "CZ75-Auto | Circaetus (Factory New)",
    "MP7 | Vault Heist (Factory New)",
    "P250 | Contaminant (Factory New)",
    "R8 Revolver | Bone Forged (Factory New)",
    "P250 | Steel Disruption (Factory New)",
    "CZ75-Auto | Tacticat (Factory New)",
    "M4A1-S | Nightmare (Factory New)",
    "SG 553 | Barricade (Factory New)",
    "AWP | Exoskeleton (Factory New)",
    "USP-S | Night Ops (Factory New)",
    "Dual Berettas | Melondrama (Field-Tested)",
    "FAMAS | Rapid Eye Movement (Battle-Scarred)",
    "Dual Berettas | Hemoglobin (Factory New)",
    "Five-SeveN | Hybrid (Factory New)",
    "USP-S | Royal Guard (Minimal Wear)",
    "P90 | Sand Spray (Factory New)",
    "Glock-18 | Gold Toof (Factory New)",
    "AWP | Atheris (Factory New)",
    "P2000 | Panther Camo (Factory New)",
    "SSG 08 | Spring Twilly (Factory New)",
    "P2000 | Imperial (Factory New)",
    "MP7 | Asterion (Factory New)",
    "CZ75-Auto | Midnight Palm (Factory New)",
    "MAC-10 | Pipsqueak (Factory New)",
    "P90 | Verdant Growth (Factory New)",
    "UMP-45 | K.O. Factory (Field-Tested)",
    "P2000 | Turf (Factory New)",
    "P250 | See Ya Later (Field-Tested)",
    "R8 Revolver | Blaze (Factory New)",
    "CZ75-Auto | Polymer (Factory New)",
    "MP9 | Deadly Poison (Factory New)",
    "AUG | Stymphalian (Field-Tested)",
    "Glock-18 | Steel Disruption (Factory New)",
    "MP9 | Orange Peel (Factory New)",
    "Glock-18 | Gamma Doppler (Minimal Wear)",
    "MAC-10 | Carnivore (Factory New)",
    "P250 | Visions (Minimal Wear)",
    "M4A4 | Neo-Noir (Field-Tested)",
    "M4A4 | Temukau (Field-Tested)",
    "AK-47 | Baroque Purple (Field-Tested)",
    "Tec-9 | Rust Leaf (Factory New)",
    "USP-S | Royal Guard (Factory New)",
    "SG 553 | Atlas (Factory New)",
    "PP-Bizon | Brass (Factory New)",
    "P250 | Asiimov (Battle-Scarred)",
    "Nova | Gila (Minimal Wear)",
    "M4A4 | Converter (Factory New)",
    "CZ75-Auto | Eco (Factory New)",
    "FAMAS | Rapid Eye Movement (Field-Tested)",
    "Dual Berettas | Flora Carnivora (Factory New)",
    "Glock-18 | Mirror Mosaic (Battle-Scarred)",
    "Tec-9 | Whiteout (Field-Tested)",
    "UMP-45 | Full Stop (Factory New)",
    "MP7 | Special Delivery (Factory New)",
    "MAG-7 | Silver (Factory New)",
    "P250 | Asiimov (Field-Tested)",
    "FAMAS | Waters of Nephthys (Factory New)",
    "G3SG1 | Stinger (Field-Tested)",
    "USP-S | Blueprint (Minimal Wear)",
    "MAC-10 | Button Masher (Factory New)",
    "MAG-7 | Bulldozer (Minimal Wear)",
    "AWP | Asiimov (Battle-Scarred)",
    "CZ75-Auto | Red Astor (Factory New)",
    "Galil AR | Urban Rubble (Factory New)",
    "SSG 08 | Dark Water (Minimal Wear)",
    "P250 | Visions (Field-Tested)",
    "P2000 | Ivory (Factory New)",
    "AWP | Chromatic Aberration (Field-Tested)",
    "AK-47 | Nouveau Rouge (Well-Worn)",
    "FAMAS | Pulse (Factory New)",
    "Nova | Wurst Hölle (Factory New)",
    "G3SG1 | Orange Kimono (Factory New)",
    "R8 Revolver | Llama Cannon (Field-Tested)",
    "MP9 | Sand Dashed (Factory New)",
    "P2000 | Amber Fade (Factory New)",
    "Galil AR | Chromatic Aberration (Factory New)",
    "Five-SeveN | Urban Hazard (Factory New)",
    "MP5-SD | Statics (Factory New)",
    "SSG 08 | Azure Glyph (Factory New)",
    "MP7 | Nemesis (Factory New)",
    "Five-SeveN | Kami (Factory New)",
    "P2000 | Pulse (Factory New)",
    "Sawed-Off | Devourer (Field-Tested)",
    "AWP | Chromatic Aberration (Minimal Wear)",
    "Dual Berettas | Urban Shock (Factory New)",
    "M4A4 | Royal Paladin (Field-Tested)",
    "M4A4 | Dark Blossom (Factory New)",
    "P250 | Mint Kimono (Factory New)",
    "FAMAS | Eye of Athena (Factory New)",
    "P2000 | Pathfinder (Factory New)",
    "MAC-10 | Palm (Factory New)",
    "StatTrak™ Five-SeveN | Case Hardened (Battle-Scarred)",
    "MAG-7 | Carbon Fiber (Factory New)",
    "SSG 08 | Red Stone (Minimal Wear)",
    "R8 Revolver | Banana Cannon (Factory New)",
    "Five-SeveN | Angry Mob (Field-Tested)",
    "Negev | Nuclear Waste (Factory New)",
    "AUG | Lil' Pig (Minimal Wear)",
    "Glock-18 | Gold Toof (Field-Tested)",
    "Desert Eagle | Urban DDPAT (Minimal Wear)",
    "AK-47 | Baroque Purple (Factory New)",
    "Sawed-Off | Bamboo Shadow (Factory New)",
    "P250 | Boreal Forest (Factory New)",
    "Galil AR | Crimson Tsunami (Factory New)",
    "Galil AR | Firefight (Factory New)",
    "M249 | Jungle (Field-Tested)",
    "XM1014 | Watchdog (Factory New)",
    "XM1014 | Scumbria (Factory New)",
    "UMP-45 | Momentum (Minimal Wear)",
    "P2000 | Space Race (Factory New)",
    "Glock-18 | Royal Legion (Factory New)",
    "AUG | Syd Mead (Minimal Wear)",
    "M4A1-S | Moss Quartz (Factory New)",
    "M4A4 | Temukau (Minimal Wear)",
    "P250 | Asiimov (Minimal Wear)",
    "MAC-10 | Echoing Sands (Factory New)",
    "StatTrak™ P250 | Visions (Field-Tested)",
    "P2000 | Dispatch (Factory New)",
    "Dual Berettas | Hydro Strike (Factory New)",
    "M4A1-S | Cyrex (Field-Tested)",
    "SG 553 | Fallout Warning (Factory New)",
    "P90 | Nostalgia (Field-Tested)",
    "Nova | Yorkshire (Factory New)",
    "Five-SeveN | Berries And Cherries (Factory New)",
    "PP-Bizon | High Roller (Factory New)",
    "MP5-SD | Agent (Factory New)",
    "CZ75-Auto | Slalom (Factory New)",
    "AWP | Duality (Minimal Wear)",
    "AK-47 | Black Laminate (Minimal Wear)",
    "M4A4 | Jungle Tiger (Minimal Wear)",
    "M4A4 | Choppa (Factory New)",
    "Glock-18 | Gamma Doppler (Field-Tested)",
    "AK-47 | Asiimov (Field-Tested)",
    "AK-47 | Emerald Pinstripe (Minimal Wear)",
    "Desert Eagle | Sputnik (Factory New)",
    "R8 Revolver | Reboot (Factory New)",
    "M4A1-S | Hyper Beast (Field-Tested)",
    "P90 | Shapewood (Field-Tested)",
    "MP7 | Fade (Factory New)",
    "MP7 | Prey (Factory New)",
    "UMP-45 | K.O. Factory (Minimal Wear)",
    "P2000 | Silver (Factory New)",
    "M4A4 | The Coalition (Well-Worn)",
    "MAC-10 | Neon Rider (Field-Tested)",
    "UMP-45 | Wild Child (Battle-Scarred)",
    "SSG 08 | Detour (Factory New)",
    "FAMAS | Neural Net (Factory New)",
    "P250 | Supernova (Factory New)",
    "Five-SeveN | Withered Vine (Factory New)",
    "Sawed-Off | Jungle Thicket (Factory New)",
    "M4A1-S | Bright Water (Minimal Wear)",
    "SSG 08 | Abyss (Factory New)",
    "MAC-10 | Rangeen (Factory New)",
    "Tec-9 | Titanium Bit (Factory New)",
    "Desert Eagle | Serpent Strike (Factory New)",
    "AK-47 | The Empress (Field-Tested)",
    "Dual Berettas | Twin Turbo (Minimal Wear)",
    "Galil AR | Eco (Minimal Wear)",
    "CZ75-Auto | Pole Position (Factory New)",
    "XM1014 | Tranquility (Factory New)",
    "M4A4 | Faded Zebra (Minimal Wear)",
    "MP7 | Abyssal Apparition (Minimal Wear)",
    "Desert Eagle | Light Rail (Factory New)",
    "CZ75-Auto | Indigo (Factory New)",
    "USP-S | Lead Conduit (Factory New)",
    "StatTrak™ FAMAS | Rapid Eye Movement (Field-Tested)",
    "PP-Bizon | High Roller (Field-Tested)",
    "StatTrak™ P250 | Visions (Minimal Wear)",
    "Five-SeveN | Capillary (Factory New)",
    "Dual Berettas | Twin Turbo (Factory New)",
    "FAMAS | Djinn (Field-Tested)",
    "P250 | Mehndi (Battle-Scarred)",
    "M4A4 | Evil Daimyo (Factory New)",
    "AUG | Eye of Zapems (Factory New)",
    "M4A1-S | Leaded Glass (Field-Tested)",
    "Desert Eagle | Ocean Drive (Field-Tested)",
    "StatTrak™ MP7 | Bloodsport (Field-Tested)",
    "M4A4 | The Coalition (Field-Tested)",
    "AK-47 | Jungle Spray (Field-Tested)",
    "M4A1-S | Vaporwave (Battle-Scarred)",
    "USP-S | Jawbreaker (Well-Worn)",
    "StatTrak™ AWP | Worm God (Field-Tested)",
    "AK-47 | Nightwish (Field-Tested)",
    "MP7 | Cirrus (Factory New)",
    "Five-SeveN | Hot Shot (Factory New)",
    "M4A4 | Magnesium (Factory New)",
    "MP9 | Hydra (Minimal Wear)",
    "AK-47 | Blue Laminate (Factory New)",
    "AUG | Plague (Factory New)",
    "MP7 | Abyssal Apparition (Field-Tested)",
    "FAMAS | Afterimage (Factory New)",
    "AK-47 | Nouveau Rouge (Battle-Scarred)",
    "PP-Bizon | Osiris (Factory New)",
    "Five-SeveN | Case Hardened (Minimal Wear)",
    "MP7 | Forest DDPAT (Factory New)",
    "FAMAS | Eye of Athena (Field-Tested)",
    "StatTrak™ Galil AR | Chromatic Aberration (Field-Tested)",
    "Desert Eagle | Mulberry (Minimal Wear)",
    "P90 | Nostalgia (Factory New)",
    "AWP | Mortis (Minimal Wear)",
    "Five-SeveN | Fowl Play (Field-Tested)",
    "M4A4 | In Living Color (Field-Tested)",
    "MAC-10 | Last Dive (Factory New)",
    "Dual Berettas | Melondrama (Minimal Wear)",
    "MP9 | Starlight Protector (Field-Tested)",
    "UMP-45 | Plastique (Factory New)",
    "MP9 | Bulldozer (Minimal Wear)",
    "MAG-7 | Heat (Factory New)",
    "Desert Eagle | Night (Minimal Wear)",
    "Galil AR | Control (Factory New)",
    "MP9 | Rose Iron (Factory New)",
    "StatTrak™ M4A1-S | Emphorosaur-S (Factory New)",
    "P250 | Cartel (Field-Tested)",
    "AK-47 | Baroque Purple (Minimal Wear)",
    "R8 Revolver | Fade (Minimal Wear)",
    "MAG-7 | Sonar (Factory New)",
    "Galil AR | Amber Fade (Factory New)",
    "Desert Eagle | Starcade (Factory New)",
    "Nova | Moon in Libra (Factory New)",
    "AK-47 | Legion of Anubis (Field-Tested)",
    "M4A1-S | Glitched Paint (Minimal Wear)",
    "Sawed-Off | Wasteland Princess (Factory New)",
    "AK-47 | Ice Coaled (Factory New)",
    "Five-SeveN | Boost Protocol (Factory New)",
    "M4A1-S | Moss Quartz (Field-Tested)",
    "P250 | Vino Primo (Minimal Wear)",
    "AK-47 | Searing Rage (Well-Worn)",
    "AWP | Mortis (Field-Tested)",
    "M4A4 | Hellish (Battle-Scarred)",
    "Glock-18 | Shinobu (Battle-Scarred)",
    "USP-S | Cortex (Minimal Wear)",
    "P250 | Muertos (Factory New)",
    "USP-S | Para Green (Factory New)",
    "Glock-18 | Dragon Tattoo (Factory New)",
    "P250 | Mint Kimono (Field-Tested)",
    "Galil AR | Sky Mandala (Factory New)",
    "StatTrak™ AWP | Asiimov (Battle-Scarred)",
    "Dual Berettas | Demolition (Field-Tested)",
    "AWP | Chrome Cannon (Field-Tested)",
    "UMP-45 | Late Night Transit (Factory New)",
    "MP5-SD | Phosphor (Minimal Wear)",
    "M4A4 | Tooth Fairy (Minimal Wear)",
    "FAMAS | Rapid Eye Movement (Minimal Wear)",
    "P250 | Inferno (Factory New)",
    "SG 553 | Cyrex (Factory New)",
    "P90 | Wave Breaker (Factory New)",
    "MP7 | Scorched (Field-Tested)",
    "SG 553 | Darkwing (Factory New)",
    "AK-47 | Jungle Spray (Minimal Wear)",
    "AWP | Exoskeleton (Minimal Wear)",
    "SSG 08 | Dragonfire (Field-Tested)",
    "AUG | Momentum (Field-Tested)",
    "Tec-9 | Urban DDPAT (Factory New)",
    "M4A1-S | Control Panel (Field-Tested)",
    "MP9 | Ruby Poison Dart (Factory New)",
    "MP5-SD | Kitbash (Factory New)",
    "MAC-10 | Disco Tech (Field-Tested)",
    "AK-47 | Safety Net (Minimal Wear)",
    "MAC-10 | Malachite (Factory New)",
    "AK-47 | Head Shot (Battle-Scarred)",
    "P250 | Franklin (Factory New)",
    "Glock-18 | Moonrise (Factory New)",
    "FAMAS | Sundown (Factory New)",
    "CZ75-Auto | Slalom (Field-Tested)",
    "MAG-7 | Copper Coated (Factory New)",
    "AK-47 | Safety Net (Field-Tested)",
    "SCAR-20 | Bloodsport (Minimal Wear)",
    "M4A4 | Cyber Security (Factory New)",
    "Galil AR | Chatterbox (Field-Tested)",
    "AWP | Ice Coaled (Field-Tested)",
    "MP5-SD | Phosphor (Field-Tested)",
    "M4A4 | Desolate Space (Factory New)",
    "M4A1-S | Black Lotus (Field-Tested)",
    "MP7 | Bloodsport (Minimal Wear)",
    "StatTrak™ Five-SeveN | Monkey Business (Field-Tested)",
    "M4A4 | Tooth Fairy (Factory New)",
    "CZ75-Auto | Vendetta (Factory New)",
    "AK-47 | Cartel (Factory New)",
    "Galil AR | Phoenix Blacklight (Factory New)",
    "AK-47 | Searing Rage (Field-Tested)",
    "FAMAS | Yeti Camo (Factory New)",
    "AK-47 | Ice Coaled (Battle-Scarred)",
    "M4A1-S | Leaded Glass (Minimal Wear)",
    "M4A1-S | Dark Water (Minimal Wear)",
    "StatTrak™ UMP-45 | Primal Saber (Field-Tested)",
    "AWP | Queen's Gambit (Well-Worn)",
    "StatTrak™ AWP | Duality (Battle-Scarred)",
    "AWP | Black Nile (Battle-Scarred)",
    "StatTrak™ M4A4 | Tooth Fairy (Minimal Wear)",
    "FAMAS | Commemoration (Field-Tested)",
    "MP7 | Impire (Factory New)",
    "Galil AR | Connexion (Factory New)",
    "Tec-9 | Fuel Injector (Field-Tested)",
    "Glock-18 | Water Elemental (Field-Tested)",
    "StatTrak™ P2000 | Wicked Sick (Minimal Wear)",
    "AK-47 | Neon Revolution (Field-Tested)",
    "P90 | Blind Spot (Factory New)",
    "P90 | Cold Blooded (Factory New)",
    "Galil AR | Chromatic Aberration (Field-Tested)",
    "Five-SeveN | Monkey Business (Minimal Wear)",
    "Five-SeveN | Anodized Gunmetal (Factory New)",
    "P2000 | Wicked Sick (Battle-Scarred)",
    "SSG 08 | Big Iron (Field-Tested)",
    "SCAR-20 | Emerald (Factory New)",
    "AK-47 | Redline (Minimal Wear)",
    "AK-47 | Breakthrough (Minimal Wear)",
    "AK-47 | Point Disarray (Factory New)",
    "P90 | ScaraB Rush (Factory New)",
    "AK-47 | Searing Rage (Battle-Scarred)",
    "CZ75-Auto | Army Sheen (Minimal Wear)",
    "P250 | Muertos (Field-Tested)",
    "P90 | Deathgaze (Well-Worn)",
    "M4A4 | Etch Lord (Factory New)",
    "Dual Berettas | Balance (Minimal Wear)",
    "Glock-18 | Vogue (Field-Tested)",
    "AK-47 | Fuel Injector (Field-Tested)",
    "R8 Revolver | Fade (Field-Tested)",
    "AWP | Ice Coaled (Well-Worn)",
    "StatTrak™ P90 | Wave Breaker (Factory New)",
    "AUG | Death by Puppy (Minimal Wear)",
    "P90 | Shallow Grave (Minimal Wear)",
    "XM1014 | XOXO (Field-Tested)",
    "Glock-18 | Mirror Mosaic (Well-Worn)",
    "G3SG1 | Dream Glade (Factory New)",
    "Glock-18 | Shinobu (Field-Tested)",
    "Desert Eagle | Crimson Web (Field-Tested)",
    "Tec-9 | Bamboozle (Factory New)",
    "MAC-10 | Nuclear Garden (Factory New)",
    "AK-47 | Aquamarine Revenge (Battle-Scarred)",
    "AK-47 | The Oligarch (Well-Worn)",
    "M4A1-S | Chantico's Fire (Battle-Scarred)",
    "USP-S | Cortex (Battle-Scarred)",
    "MAC-10 | Fade (Factory New)",
    "AWP | Ice Coaled (Battle-Scarred)",
    "USP-S | 27 (Factory New)",
    "AK-47 | Crossfade (Factory New)",
    "AWP | Sun in Leo (Factory New)",
    "Desert Eagle | Hypnotic (Factory New)",
    "FAMAS | Bad Trip (Field-Tested)",
    "M4A4 | The Battlestar (Minimal Wear)",
    "Desert Eagle | Heat Treated (Minimal Wear)",
    "USP-S | Ticket to Hell (Factory New)",
    "AK-47 | Slate (Field-Tested)",
    "AWP | Electric Hive (Factory New)",
    "AK-47 | Midnight Laminate (Minimal Wear)",
    "Glock-18 | Shinobu (Well-Worn)",
    "P250 | Red Tide (Factory New)",
    "AK-47 | Elite Build (Factory New)",
    "AK-47 | Panthera onca (Minimal Wear)",
    "MAC-10 | Saibā Oni (Factory New)",
    "AK-47 | Emerald Pinstripe (Field-Tested)",
    "AK-47 | Inheritance (Field-Tested)",
    "AK-47 | Wintergreen (Factory New)",
    "StatTrak™ AK-47 | Phantom Disruptor (Minimal Wear)",
    "StatTrak™ AK-47 | Slate (Field-Tested)",
    "USP-S | Royal Blue (Minimal Wear)",
    "Nova | Rising Skull (Factory New)",
    "MAG-7 | BI83 Spectrum (Factory New)",
    "AWP | Duality (Battle-Scarred)",
    "SG 553 | Candy Apple (Factory New)",
    "Galil AR | Kami (Factory New)",
    "P250 | Wingshot (Factory New)",
    "StatTrak™ AK-47 | Aquamarine Revenge (Minimal Wear)",
    "MAC-10 | Neon Rider (Minimal Wear)",
    "Desert Eagle | Mecha Industries (Field-Tested)",
    "M4A4 | Tooth Fairy (Field-Tested)",
    "MP9 | Setting Sun (Minimal Wear)",
    "StatTrak™ AWP | Neo-Noir (Field-Tested)",
    "P90 | Shallow Grave (Field-Tested)",
    "AUG | Navy Murano (Minimal Wear)",
    "UMP-45 | Wild Child (Factory New)",
    "StatTrak™ Glock-18 | Vogue (Field-Tested)",
    "FAMAS | Djinn (Factory New)",
    "StatTrak™ P2000 | Wicked Sick (Field-Tested)",
    "StatTrak™ AWP | Chromatic Aberration (Minimal Wear)",
    "AWP | Crakow! (Factory New)",
    "USP-S | Printstream (Field-Tested)",
    "AK-47 | Neon Rider (Factory New)",
    "AK-47 | The Oligarch (Field-Tested)",
    "SSG 08 | Big Iron (Factory New)",
    "P250 | Forest Night (Factory New)",
    "FAMAS | Night Borre (Minimal Wear)",
    "StatTrak™ UMP-45 | K.O. Factory (Field-Tested)",
    "M4A1-S | Decimator (Factory New)",
    "AK-47 | Crossfade (Minimal Wear)",
    "M4A1-S | Flashback (Minimal Wear)",
    "SCAR-20 | Bloodsport (Field-Tested)",
    "P90 | Elite Build (Factory New)",
    "AK-47 | Searing Rage (Factory New)",
    "P2000 | Wicked Sick (Minimal Wear)",
    "Tec-9 | Fuel Injector (Battle-Scarred)",
    "AK-47 | Slate (Minimal Wear)",
    "StatTrak™ AWP | Ice Coaled (Well-Worn)",
    "P2000 | Wicked Sick (Factory New)",
    "FAMAS | Mecha Industries (Minimal Wear)",
    "AK-47 | Inheritance (Factory New)",
    "Galil AR | Cerberus (Factory New)",
    "Tec-9 | Toxic (Minimal Wear)",
    "AWP | Fever Dream (Field-Tested)",
    "MP9 | Hypnotic (Factory New)",
    "SSG 08 | Parallax (Factory New)",
    "Dual Berettas | Royal Consorts (Field-Tested)",
    "Sawed-Off | Wasteland Princess (Minimal Wear)",
    "Glock-18 | AXIA (Field-Tested)",
    "Nova | Red Quartz (Field-Tested)",
    "AWP | Printstream (Well-Worn)",
    "Desert Eagle | Printstream (Field-Tested)",
    "StatTrak™ AK-47 | Elite Build (Field-Tested)",
    "USP-S | Cyrex (Minimal Wear)",
    "MP9 | Starlight Protector (Battle-Scarred)",
    "Glock-18 | Blue Fissure (Minimal Wear)",
    "AK-47 | Legion of Anubis (Minimal Wear)",
    "StatTrak™ Five-SeveN | Buddy (Minimal Wear)",
    "StatTrak™ Glock-18 | Shinobu (Battle-Scarred)",
    "USP-S | Jawbreaker (Field-Tested)",
    "MP9 | Airlock (Field-Tested)",
    "Desert Eagle | Conspiracy (Minimal Wear)",
    "MP7 | Olive Plaid (Factory New)",
    "P90 | Death by Kitty (Minimal Wear)",
    "StatTrak™ USP-S | Flashback (Factory New)",
    "AK-47 | B the Monster (Minimal Wear)",
    "M4A1-S | Stratosphere (Factory New)",
    "USP-S | Guardian (Factory New)",
    "AK-47 | Nightwish (Well-Worn)",
    "M4A1-S | Player Two (Factory New)",
    "MP7 | Armor Core (Factory New)",
    "P250 | Crimson Kimono (Factory New)",
    "M4A4 | Buzz Kill (Field-Tested)",
    "M4A4 | Spider Lily (Factory New)",
    "AK-47 | Redline (Field-Tested)",
    "MP9 | Capillary (Factory New)",
    "AWP | Exoskeleton (Battle-Scarred)",
    "AK-47 | Phantom Disruptor (Factory New)",
    "Glock-18 | Reactor (Factory New)",
    "StatTrak™ USP-S | Guardian (Field-Tested)",
    "USP-S | Jawbreaker (Battle-Scarred)",
    "StatTrak™ USP-S | Kill Confirmed (Field-Tested)",
    "StatTrak™ SG 553 | Pulse (Field-Tested)",
    "StatTrak™ AWP | Duality (Field-Tested)",
    "Five-SeveN | Copper Galaxy (Factory New)",
    "Galil AR | Rocket Pop (Factory New)",
    "AK-47 | Phantom Disruptor (Field-Tested)",
    "Glock-18 | Gold Toof (Minimal Wear)",
    "Galil AR | Signal (Factory New)",
    "SG 553 | Triarch (Factory New)",
    "M4A4 | Full Throttle (Minimal Wear)",
    "SG 553 | Integrale (Field-Tested)",
    "AK-47 | Inheritance (Battle-Scarred)",
    "P250 | Visions (Factory New)",
    "Desert Eagle | Printstream (Battle-Scarred)",
    "Galil AR | Cerberus (Field-Tested)",
    "StatTrak™ M4A1-S | Black Lotus (Field-Tested)",
    "SSG 08 | Threat Detected (Factory New)",
    "P250 | Kintsugi (Well-Worn)",
    "M4A1-S | Solitude (Factory New)",
    "AK-47 | Rat Rod (Factory New)",
    "M4A1-S | Electrum (Minimal Wear)",
    "P2000 | Wicked Sick (Well-Worn)",
    "Glock-18 | Coral Bloom (Factory New)",
    "Glock-18 | Water Elemental (Factory New)",
    "Desert Eagle | Golden Koi (Factory New)",
    "M4A1-S | Vaporwave (Field-Tested)",
    "UMP-45 | Crimson Foil (Field-Tested)",
    "USP-S | The Traitor (Well-Worn)",
    "AK-47 | Nouveau Rouge (Factory New)",
    "R8 Revolver | Grip (Factory New)",
    "AWP | Hyper Beast (Field-Tested)",
    "AK-47 | Rat Rod (Field-Tested)",
    "AWP | Chrome Cannon (Battle-Scarred)",
    "M4A4 | Desert-Strike (Field-Tested)",
    "StatTrak™ M4A1-S | Cyrex (Field-Tested)",
    "AK-47 | The Empress (Battle-Scarred)",
    "PP-Bizon | Lumen (Factory New)",
    "P90 | Astral Jörmungandr (Factory New)",
    "MP7 | Abyssal Apparition (Battle-Scarred)",
    "M4A1-S | Guardian (Factory New)",
    "AK-47 | Head Shot (Well-Worn)",
    "AK-47 | Slate (Factory New)",
    "M4A1-S | Electrum (Field-Tested)",
    "StatTrak™ AK-47 | Nightwish (Field-Tested)",
    "MAC-10 | Stalker (Minimal Wear)",
    "USP-S | Cortex (Well-Worn)",
    "USP-S | Overgrowth (Field-Tested)",
    "AK-47 | Slate (Battle-Scarred)",
    "Dual Berettas | Melondrama (Factory New)",
    "StatTrak™ AK-47 | Elite Build (Well-Worn)",
    "AK-47 | Bloodsport (Field-Tested)",
    "M4A1-S | Golden Coil (Battle-Scarred)",
    "M4A1-S | Decimator (Field-Tested)",
    "M4A1-S | Hyper Beast (Well-Worn)",
    "SG 553 | Tiger Moth (Factory New)",
    "Galil AR | Chromatic Aberration (Minimal Wear)",
    "MAC-10 | Cat Fight (Factory New)",
    "M4A1-S | Chantico's Fire (Field-Tested)",
    "AK-47 | Ice Coaled (Field-Tested)",
    "Five-SeveN | Heat Treated (Minimal Wear)",
    "AK-47 | Leet Museo (Field-Tested)",
    "Galil AR | Rainbow Spoon (Factory New)",
    "USP-S | Cyrex (Field-Tested)",
    "SG 553 | Barricade (Minimal Wear)",
    "StatTrak™ Glock-18 | Water Elemental (Minimal Wear)",
    "Desert Eagle | Mecha Industries (Minimal Wear)",
    "AK-47 | Slate (Well-Worn)",
    "Glock-18 | Ramese's Reach (Factory New)",
    "Galil AR | Eco (Field-Tested)",
    "Glock-18 | Sacrifice (Factory New)",
    "Glock-18 | Vogue (Minimal Wear)",
    "FAMAS | Bad Trip (Well-Worn)",
    "StatTrak™ Glock-18 | Vogue (Minimal Wear)",
    "AK-47 | Wasteland Rebel (Field-Tested)",
    "P90 | Nostalgia (Minimal Wear)",
    "FAMAS | Valence (Factory New)",
    "P90 | Asiimov (Minimal Wear)",
    "XM1014 | XOXO (Well-Worn)",
    "Tec-9 | Whiteout (Minimal Wear)",
    "M4A1-S | Cyrex (Minimal Wear)",
    "AK-47 | Head Shot (Minimal Wear)",
    "AUG | Random Access (Factory New)",
    "P250 | Contamination (Factory New)",
    "AK-47 | Point Disarray (Field-Tested)",
    "USP-S | Blueprint (Field-Tested)",
    "M4A1-S | Golden Coil (Field-Tested)",
    "AK-47 | Aquamarine Revenge (Field-Tested)",
    "Galil AR | Tuxedo (Factory New)",
    "UMP-45 | Crimson Foil (Factory New)",
    "USP-S | The Traitor (Field-Tested)",
    "MAC-10 | Heat (Factory New)",
    "StatTrak™ Galil AR | Galigator (Minimal Wear)",
    "USP-S | Black Lotus (Minimal Wear)",
    "AWP | Printstream (Field-Tested)",
    "USP-S | Orion (Factory New)",
    "PP-Bizon | Judgement of Anubis (Field-Tested)",
    "AWP | Green Energy (Factory New)",
    "Five-SeveN | Heat Treated (Well-Worn)",
    "AK-47 | Rat Rod (Minimal Wear)",
    "USP-S | Serum (Factory New)",
    "StatTrak™ FAMAS | Rapid Eye Movement (Minimal Wear)",
    "P250 | Kintsugi (Field-Tested)",
    "P90 | Asiimov (Well-Worn)",
    "AK-47 | Ice Coaled (Minimal Wear)",
    "FAMAS | Rapid Eye Movement (Factory New)",
    "StatTrak™ AWP | Mortis (Field-Tested)",
    "P250 | Kintsugi (Minimal Wear)",
    "M4A1-S | Printstream (Field-Tested)",
    "PP-Bizon | High Roller (Minimal Wear)",
    "Sawed-Off | Kiss♥Love (Battle-Scarred)",
    "USP-S | Cortex (Field-Tested)",
    "AUG | Fleet Flock (Field-Tested)",
    "USP-S | Whiteout (Minimal Wear)",
    "MP7 | Fade (Field-Tested)",
    "AK-47 | Vulcan (Field-Tested)",
    "AWP | Black Nile (Minimal Wear)",
    "Five-SeveN | Heat Treated (Factory New)",
    "M4A1-S | Player Two (Battle-Scarred)",
    "FAMAS | ZX Spectron (Factory New)",
    "FAMAS | Rapid Eye Movement (Well-Worn)",
    "Glock-18 | Shinobu (Minimal Wear)",
    "Glock-18 | Block-18 (Factory New)",
    "UMP-45 | Scaffold (Factory New)",
    "SSG 08 | Blood in the Water (Minimal Wear)",
    "Galil AR | Aqua Terrace (Factory New)",
    "M4A1-S | Control Panel (Minimal Wear)",
    "AWP | Mortis (Factory New)",
    "USP-S | Black Lotus (Factory New)",
    "SG 553 | Integrale (Battle-Scarred)",
    "StatTrak™ M4A4 | The Battlestar (Field-Tested)",
    "MP7 | Abyssal Apparition (Well-Worn)",
    "AWP | BOOM (Minimal Wear)",
    "StatTrak™ AK-47 | Legion of Anubis (Field-Tested)",
    "UMP-45 | Primal Saber (Factory New)",
    "StatTrak™ M4A1-S | Black Lotus (Minimal Wear)",
    "XM1014 | Incinegator (Field-Tested)",
    "StatTrak™ AWP | Duality (Minimal Wear)",
    "XM1014 | XOXO (Minimal Wear)",
    "Nova | Graphite (Factory New)",
    "AK-47 | The Empress (Factory New)",
    "AWP | Neo-Noir (Field-Tested)",
    "Glock-18 | Snack Attack (Field-Tested)",
    "M4A4 | Polysoup (Field-Tested)",
    "P250 | Whiteout (Minimal Wear)",
    "M4A4 | Neo-Noir (Minimal Wear)",
    "StatTrak™ AK-47 | Phantom Disruptor (Field-Tested)",
    "Sawed-Off | Kiss♥Love (Field-Tested)",
    "M4A1-S | Glitched Paint (Factory New)",
    "M4A1-S | Basilisk (Minimal Wear)",
    "MP7 | Bloodsport (Field-Tested)",
    "M4A4 | Eye of Horus (Battle-Scarred)",
    "StatTrak™ AWP | Worm God (Minimal Wear)",
    "FAMAS | Waters of Nephthys (Field-Tested)",
    "M4A1-S | Nitro (Factory New)",
    "P250 | Black & Tan (Factory New)",
    "AK-47 | Aquamarine Revenge (Minimal Wear)",
    "AWP | Queen's Gambit (Field-Tested)",
    "AUG | Death by Puppy (Field-Tested)",
    "Galil AR | Stone Cold (Factory New)",
    "AK-47 | Frontside Misty (Factory New)",
    "StatTrak™ AUG | Stymphalian (Field-Tested)",
    "M4A4 | Hellfire (Minimal Wear)",
    "M4A1-S | Printstream (Well-Worn)",
    "MAG-7 | Bulldozer (Field-Tested)",
    "M4A1-S | Black Lotus (Factory New)",
    "FAMAS | Waters of Nephthys (Minimal Wear)",
    "Five-SeveN | Heat Treated (Field-Tested)",
    "Desert Eagle | Mecha Industries (Factory New)",
    "AWP | Hyper Beast (Factory New)",
    "M4A1-S | Decimator (Minimal Wear)",
    "Dual Berettas | Royal Consorts (Minimal Wear)",
    "P90 | Shallow Grave (Factory New)",
    "AWP | Atheris (Well-Worn)",
    "StatTrak™ M4A4 | Desert-Strike (Field-Tested)",
    "AK-47 | Frontside Misty (Field-Tested)",
    "Sawed-Off | Wasteland Princess (Field-Tested)",
    "AWP | Wildfire (Field-Tested)",
    "Glock-18 | Green Line (Factory New)",
    "Desert Eagle | Conspiracy (Field-Tested)",
    "AK-47 | Nightwish (Factory New)",
    "M4A4 | Desert-Strike (Minimal Wear)",
    "Desert Eagle | Mint Fan (Factory New)",
    "Sawed-Off | The Kraken (Minimal Wear)",
    "StatTrak™ M4A1-S | Leaded Glass (Field-Tested)",
    "StatTrak™ M4A1-S | Cyrex (Factory New)",
    "P90 | Attack Vector (Minimal Wear)",
    "AWP | Green Energy (Battle-Scarred)",
    "Dual Berettas | Cobra Strike (Minimal Wear)",
    "MP9 | Arctic Tri-Tone (Field-Tested)",
    "FAMAS | Commemoration (Minimal Wear)",
    "MP9 | Mount Fuji (Field-Tested)",
    "M4A4 | Asiimov (Battle-Scarred)",
    "Galil AR | Dusk Ruins (Factory New)",
    "AWP | Redline (Minimal Wear)",
    "MAC-10 | Surfwood (Field-Tested)",
    "Tec-9 | Isaac (Factory New)",
    "SSG 08 | Dragonfire (Minimal Wear)",
    "AK-47 | Phantom Disruptor (Battle-Scarred)",
    "StatTrak™ Zeus x27 | Olympus (Field-Tested)",
    "M4A1-S | Flashback (Field-Tested)",
    "StatTrak™ AWP | PAW (Field-Tested)",
    "M4A1-S | Leaded Glass (Well-Worn)",
    "Glock-18 | Neo-Noir (Field-Tested)",
    "AK-47 | The Empress (Well-Worn)",
    "AWP | PAW (Factory New)",
    "M4A1-S | Master Piece (Minimal Wear)",
    "Glock-18 | Fully Tuned (Well-Worn)",
    "MAG-7 | Justice (Field-Tested)",
    "MP5-SD | Desert Strike (Factory New)",
    "USP-S | Guardian (Minimal Wear)",
    "StatTrak™ AK-47 | Searing Rage (Field-Tested)",
    "SG 553 | Gator Mesh (Factory New)",
    "FAMAS | Styx (Field-Tested)",
    "AK-47 | Midnight Laminate (Battle-Scarred)",
    "AWP | Atheris (Minimal Wear)",
    "M4A1-S | Decimator (Battle-Scarred)",
    "AK-47 | Crane Flight (Field-Tested)",
    "StatTrak™ P90 | Asiimov (Field-Tested)",
    "M4A1-S | Flashback (Well-Worn)",
    "AK-47 | Blue Laminate (Minimal Wear)",
    "AUG | Lil' Pig (Field-Tested)",
    "StatTrak™ Glock-18 | Shinobu (Minimal Wear)",
    "AUG | Spalted Wood (Factory New)",
    "AUG | Stymphalian (Minimal Wear)",
    "P90 | Glacier Mesh (Minimal Wear)",
    "SG 553 | Colony IV (Factory New)",
    "StatTrak™ AK-47 | Searing Rage (Battle-Scarred)",
    "Galil AR | Cerberus (Minimal Wear)",
    "M4A1-S | Nightmare (Well-Worn)",
    "AK-47 | Point Disarray (Minimal Wear)",
    "StatTrak™ M4A4 | Tooth Fairy (Field-Tested)",
    "AK-47 | The Outsiders (Well-Worn)",
    "Tec-9 | Fuel Injector (Well-Worn)",
    "Desert Eagle | Code Red (Minimal Wear)",
    "M4A4 | Griffin (Field-Tested)",
    "AK-47 | Orbit Mk01 (Factory New)",
    "AWP | LongDog (Field-Tested)",
    "Dual Berettas | Melondrama (Well-Worn)",
    "Glock-18 | Twilight Galaxy (Minimal Wear)",
    "M4A1-S | Basilisk (Factory New)",
    "USP-S | Kill Confirmed (Field-Tested)",
    "MP9 | Arctic Tri-Tone (Factory New)",
    "AK-47 | Blue Laminate (Field-Tested)",
    "AWP | POP AWP (Field-Tested)",
    "Negev | Boroque Sand (Factory New)",
    "StatTrak™ MP7 | Abyssal Apparition (Field-Tested)",
    "SSG 08 | Turbo Peek (Field-Tested)",
    "AWP | Fever Dream (Factory New)",
    "AWP | PAW (Minimal Wear)",
    "StatTrak™ XM1014 | XOXO (Field-Tested)",
    "AK-47 | Bloodsport (Minimal Wear)",
    "Tec-9 | Blue Titanium (Factory New)",
    "AK-47 | The Oligarch (Battle-Scarred)",
    "AWP | Crakow! (Well-Worn)",
    "M249 | Humidor (Minimal Wear)",
    "USP-S | Monster Mashup (Factory New)",
    "Glock-18 | Bullet Queen (Field-Tested)",
    "M4A4 | Eye of Horus (Field-Tested)",
    "SG 553 | Berry Gel Coat (Factory New)",
    "AWP | Containment Breach (Field-Tested)",
    "AWP | Crakow! (Battle-Scarred)",
    "AWP | Pink DDPAT (Field-Tested)",
    "MP9 | Setting Sun (Field-Tested)",
    "UMP-45 | Blaze (Factory New)",
    "MP9 | Music Box (Factory New)",
    "Five-SeveN | Withered Vine (Field-Tested)",
    "StatTrak™ MAC-10 | Neon Rider (Field-Tested)",
    "USP-S | Printstream (Minimal Wear)",
    "P250 | Nevermore (Factory New)",
    "Glock-18 | Water Elemental (Minimal Wear)",
    "Desert Eagle | Conspiracy (Factory New)",
    "SSG 08 | Turbo Peek (Factory New)",
    "StatTrak™ MP7 | Bloodsport (Minimal Wear)",
    "StatTrak™ UMP-45 | K.O. Factory (Well-Worn)",
    "XM1014 | Ziggy (Factory New)",
    "StatTrak™ M4A1-S | Black Lotus (Well-Worn)",
    "MP9 | Food Chain (Field-Tested)",
    "AWP | Asiimov (Field-Tested)",
    "P250 | Mehndi (Well-Worn)",
    "SG 553 | Dragon Tech (Factory New)",
    "FAMAS | Commemoration (Factory New)",
    "StatTrak™ SSG 08 | Blood in the Water (Minimal Wear)",
    "CZ75-Auto | Victoria (Minimal Wear)",
    "StatTrak™ P2000 | Wicked Sick (Battle-Scarred)",
    "AWP | CMYK (Field-Tested)",
    "CZ75-Auto | Syndicate (Field-Tested)",
    "AWP | Containment Breach (Well-Worn)",
    "Desert Eagle | Code Red (Field-Tested)",
    "USP-S | Kill Confirmed (Battle-Scarred)",
    "Five-SeveN | Boost Protocol (Field-Tested)",
    "Tec-9 | Bamboo Forest (Minimal Wear)",
    "StatTrak™ MP7 | Abyssal Apparition (Minimal Wear)",
    "UMP-45 | Neo-Noir (Well-Worn)",
    "USP-S | Whiteout (Field-Tested)",
    "M4A1-S | Vaporwave (Factory New)",
    "M4A1-S | Black Lotus (Well-Worn)",
    "AWP | Atheris (Battle-Scarred)",
    "StatTrak™ USP-S | Jawbreaker (Field-Tested)",
    "SSG 08 | Death's Head (Factory New)",
    "AK-47 | Nightwish (Minimal Wear)",
    "Dual Berettas | Melondrama (Battle-Scarred)",
    "MAC-10 | Stalker (Field-Tested)",
    "P2000 | Fire Elemental (Field-Tested)",
    "StatTrak™ MP7 | Special Delivery (Minimal Wear)",
    "P250 | Epicenter (Factory New)",
    "Desert Eagle | Mecha Industries (Well-Worn)",
    "P2000 | Scorpion (Factory New)",
    "AK-47 | Emerald Pinstripe (Battle-Scarred)",
    "StatTrak™ Desert Eagle | Light Rail (Field-Tested)",
    "P250 | Undertow (Factory New)",
    "Desert Eagle | Crimson Web (Factory New)",
    "PP-Bizon | Antique (Factory New)",
    "Dual Berettas | Panther (Minimal Wear)",
    "StatTrak™ AK-47 | Wasteland Rebel (Field-Tested)",
    "Tec-9 | Avalanche (Factory New)",
    "AK-47 | Red Laminate (Minimal Wear)",
    "M4A1-S | Hyper Beast (Battle-Scarred)",
    "Desert Eagle | Mulberry (Factory New)",
    "Glock-18 | Fully Tuned (Battle-Scarred)",
    "M4A1-S | Flashback (Battle-Scarred)",
    "StatTrak™ AK-47 | Bloodsport (Minimal Wear)",
    "AWP | Electric Hive (Minimal Wear)",
    "AK-47 | Vulcan (Well-Worn)",
    "P250 | Mehndi (Minimal Wear)",
    "StatTrak™ Dual Berettas | Melondrama (Minimal Wear)",
    "Galil AR | Chatterbox (Well-Worn)",
    "AK-47 | Aphrodite (Minimal Wear)",
    "AWP | Black Nile (Field-Tested)",
    "MP7 | Bloodsport (Factory New)",
    "M4A4 | Cyber Security (Minimal Wear)",
    "AWP | Exothermic (Factory New)",
    "StatTrak™ USP-S | Cyrex (Factory New)",
    "StatTrak™ USP-S | Jawbreaker (Battle-Scarred)",
    "PP-Bizon | Urban Dashed (Factory New)",
    "CZ75-Auto | Yellow Jacket (Factory New)",
    "USP-S | Stainless (Factory New)",
    "StatTrak™ AK-47 | Ice Coaled (Field-Tested)",
    "M4A1-S | Hyper Beast (Factory New)",
    "M4A4 | Bullet Rain (Field-Tested)",
    "M4A1-S | Black Lotus (Minimal Wear)",
    "StatTrak™ MP9 | Food Chain (Minimal Wear)",
    "Galil AR | Rainbow Spoon (Field-Tested)",
    "StatTrak™ M4A1-S | Night Terror (Factory New)",
    "StatTrak™ AWP | Fever Dream (Factory New)",
    "XM1014 | Entombed (Factory New)",
    "M4A1-S | Mecha Industries (Field-Tested)",
    "Glock-18 | Reactor (Minimal Wear)",
    "AK-47 | Neon Rider (Field-Tested)",
    "P250 | Epicenter (Field-Tested)",
    "M4A1-S | Nightmare (Battle-Scarred)",
    "StatTrak™ AWP | Mortis (Minimal Wear)",
    "P250 | Asiimov (Well-Worn)",
    "AK-47 | Green Laminate (Factory New)",
    "Glock-18 | Fully Tuned (Minimal Wear)",
    "AWP | Hyper Beast (Well-Worn)",
    "Desert Eagle | Ocean Drive (Battle-Scarred)",
    "StatTrak™ M4A4 | Tooth Fairy (Battle-Scarred)",
    "StatTrak™ Glock-18 | Grinder (Minimal Wear)",
    "M4A4 | Temukau (Factory New)",
    "StatTrak™ MP9 | Hypnotic (Factory New)",
    "P250 | See Ya Later (Factory New)",
    "FAMAS | Spitfire (Field-Tested)",
    "Desert Eagle | Directive (Minimal Wear)",
    "SSG 08 | Dragonfire (Factory New)",
    "StatTrak™ AWP | Worm God (Factory New)",
    "Galil AR | Chatterbox (Battle-Scarred)",
    "MP9 | Food Chain (Well-Worn)",
    "StatTrak™ MAC-10 | Disco Tech (Field-Tested)",
    "Five-SeveN | Angry Mob (Factory New)",
    "M4A4 | Radiation Hazard (Minimal Wear)",
    "SSG 08 | Rapid Transit (Factory New)",
    "AK-47 | Wintergreen (Minimal Wear)",
    "USP-S | Alpine Camo (Factory New)",
    "Galil AR | Tornado (Field-Tested)",
    "StatTrak™ USP-S | Cortex (Minimal Wear)",
    "AK-47 | First Class (Field-Tested)",
    "M4A4 | Griffin (Factory New)",
    "Five-SeveN | Orange Peel (Factory New)",
    "AWP | Printstream (Minimal Wear)",
    "P250 | Digital Architect (Factory New)",
    "Desert Eagle | Trigger Discipline (Factory New)",
    "P90 | Desert Warfare (Factory New)",
    "USP-S | Jawbreaker (Factory New)",
    "SSG 08 | Necropos (Factory New)",
    "AK-47 | Aphrodite (Factory New)",
    "AK-47 | Breakthrough (Factory New)",
    "AK-47 | Point Disarray (Battle-Scarred)",
    "AWP | POP AWP (Well-Worn)",
    "AWP | Pink DDPAT (Minimal Wear)",
    "StatTrak™ USP-S | Dark Water (Minimal Wear)",
    "StatTrak™ MAC-10 | Saibā Oni (Minimal Wear)",
    "StatTrak™ AWP | Mortis (Factory New)",
    "StatTrak™ MP9 | Starlight Protector (Field-Tested)",
    "Galil AR | Chromatic Aberration (Well-Worn)",
    "AK-47 | Ice Coaled (Well-Worn)",
    "StatTrak™ AWP | Chromatic Aberration (Field-Tested)",
    "AK-47 | Wasteland Rebel (Minimal Wear)",
    "StatTrak™ M4A1-S | Leaded Glass (Minimal Wear)",
    "M4A1-S | Master Piece (Field-Tested)",
    "AK-47 | Jaguar (Minimal Wear)",
    "StatTrak™ M4A4 | Tooth Fairy (Factory New)",
    "AK-47 | Cartel (Minimal Wear)",
    "AK-47 | Fuel Injector (Battle-Scarred)",
    "AK-47 | Fuel Injector (Minimal Wear)",
    "StatTrak™ USP-S | Neo-Noir (Field-Tested)",
    "M4A1-S | Flashback (Factory New)",
    "StatTrak™ UMP-45 | K.O. Factory (Factory New)",
    "StatTrak™ AK-47 | Searing Rage (Well-Worn)",
    "Tec-9 | Fuel Injector (Factory New)",
    "P90 | Asiimov (Battle-Scarred)",
    "AWP | Neo-Noir (Minimal Wear)",
    "AK-47 | The Oligarch (Minimal Wear)",
    "USP-S | Printstream (Battle-Scarred)",
    "AK-47 | The Empress (Minimal Wear)",
    "MP9 | Airlock (Minimal Wear)",
    "StatTrak™ USP-S | Blood Tiger (Minimal Wear)",
    "StatTrak™ M4A4 | Temukau (Field-Tested)",
    "PP-Bizon | Fuel Rod (Factory New)",
    "AK-47 | Panthera onca (Field-Tested)",
    "StatTrak™ XM1014 | XOXO (Minimal Wear)",
    "Glock-18 | Brass (Battle-Scarred)",
    "M4A4 | Neo-Noir (Battle-Scarred)",
    "P2000 | Fire Elemental (Minimal Wear)",
    "CZ75-Auto | Tread Plate (Factory New)",
    "StatTrak™ Glock-18 | Dragon Tattoo (Factory New)",
    "MP9 | Arctic Tri-Tone (Battle-Scarred)",
    "StatTrak™ AK-47 | Bloodsport (Field-Tested)",
    "P250 | See Ya Later (Minimal Wear)",
    "M4A4 | Radiation Hazard (Field-Tested)",
    "StatTrak™ SSG 08 | Big Iron (Field-Tested)",
    "Desert Eagle | Starcade (Minimal Wear)",
    "AWP | Chrome Cannon (Factory New)",
    "Desert Eagle | Naga (Factory New)",
    "UMP-45 | K.O. Factory (Well-Worn)",
    "MAG-7 | SWAG-7 (Factory New)",
    "AK-47 | Phantom Disruptor (Minimal Wear)",
    "MP9 | Starlight Protector (Minimal Wear)",
    "Glock-18 | Vogue (Factory New)",
    "AK-47 | The Outsiders (Field-Tested)",
    "StatTrak™ Glock-18 | Shinobu (Well-Worn)",
    "M4A1-S | Fade (Factory New)",
    "StatTrak™ M4A4 | Turbine (Field-Tested)",
    "StatTrak™ Zeus x27 | Tosai (Factory New)",
    "AWP | Redline (Field-Tested)",
    "P2000 | Imperial Dragon (Factory New)",
    "P90 | Deathgaze (Minimal Wear)",
    "Glock-18 | Brass (Minimal Wear)",
    "StatTrak™ Desert Eagle | Conspiracy (Minimal Wear)",
    "FAMAS | Roll Cage (Field-Tested)",
    "Nova | Antique (Factory New)",
    "M4A4 | Full Throttle (Battle-Scarred)",
    "M4A4 | Poly Mag (Factory New)",
    "Desert Eagle | Kumicho Dragon (Field-Tested)",
    "M4A1-S | Hyper Beast (Minimal Wear)",
    "Negev | Lionfish (Factory New)",
    "Glock-18 | Snack Attack (Battle-Scarred)",
    "Galil AR | Sugar Rush (Field-Tested)",
    "SSG 08 | Bloodshot (Field-Tested)",
    "SSG 08 | Blood in the Water (Factory New)",
    "StatTrak™ SSG 08 | Rapid Transit (Minimal Wear)",
    "USP-S | Neo-Noir (Factory New)",
    "MP9 | Urban Sovereign (Factory New)",
    "Dual Berettas | Sweet Little Angels (Field-Tested)",
    "StatTrak™ USP-S | Ticket to Hell (Factory New)",
    "Desert Eagle | Printstream (Minimal Wear)",
    "M4A4 | Evil Daimyo (Field-Tested)",
    "M4A1-S | Golden Coil (Well-Worn)",
    "SG 553 | Desert Blossom (Factory New)",
    "StatTrak™ MP5-SD | Phosphor (Factory New)",
    "M4A1-S | Atomic Alloy (Minimal Wear)",
    "M4A4 | Spider Lily (Field-Tested)",
    "AWP | Atheris (Field-Tested)",
    "AK-47 | Vulcan (Battle-Scarred)",
    "MAC-10 | Propaganda (Field-Tested)",
    "M4A1-S | Chantico's Fire (Factory New)",
    "StatTrak™ Glock-18 | Shinobu (Factory New)",
    "M4A1-S | Briefing (Factory New)",
    "StatTrak™ AWP | Ice Coaled (Battle-Scarred)",
    "USP-S | Neo-Noir (Field-Tested)",
    "AUG | Syd Mead (Factory New)",
    "Galil AR | Eco (Well-Worn)",
    "USP-S | Blueprint (Factory New)",
    "M249 | Emerald Poison Dart (Factory New)",
    "Glock-18 | Grinder (Minimal Wear)",
    "StatTrak™ MP9 | Starlight Protector (Battle-Scarred)",
    "AK-47 | Case Hardened (Battle-Scarred)",
    "AK-47 | Nouveau Rouge (Field-Tested)",
    "M4A1-S | Printstream (Battle-Scarred)",
    "AK-47 | The Outsiders (Factory New)",
    "USP-S | Purple DDPAT (Minimal Wear)",
    "R8 Revolver | Memento (Factory New)",
    "Tec-9 | Remote Control (Factory New)",
    "AWP | Chrome Cannon (Well-Worn)",
    "Glock-18 | Trace Lock (Factory New)",
    "P90 | Deathgaze (Field-Tested)",
    "MP7 | Nemesis (Field-Tested)",
    "StatTrak™ M4A1-S | Player Two (Minimal Wear)",
    "StatTrak™ AWP | Neo-Noir (Minimal Wear)",
    "StatTrak™ SSG 08 | Turbo Peek (Factory New)",
    "AK-47 | Legion of Anubis (Battle-Scarred)",
    "UMP-45 | K.O. Factory (Battle-Scarred)",
    "Tec-9 | Decimator (Factory New)",
    "Glock-18 | Neo-Noir (Well-Worn)",
    "M4A1-S | Solitude (Minimal Wear)",
    "StatTrak™ Glock-18 | Water Elemental (Field-Tested)",
    "MP5-SD | Bamboo Garden (Factory New)",
    "AK-47 | Elite Build (Minimal Wear)",
    "UMP-45 | Wild Child (Minimal Wear)",
    "P250 | Muertos (Minimal Wear)",
    "P250 | Cartel (Factory New)",
    "M4A1-S | Leaded Glass (Factory New)",
    "MP9 | Hydra (Factory New)",
    "MP9 | Bulldozer (Field-Tested)",
    "AK-47 | B the Monster (Field-Tested)",
    "StatTrak™ USP-S | Guardian (Factory New)",
    "AK-47 | Case Hardened (Field-Tested)",
    "P2000 | Fire Elemental (Battle-Scarred)",
    "AK-47 | Fuel Injector (Well-Worn)",
    "Glock-18 | Nuclear Garden (Minimal Wear)",
    "Nova | Rising Sun (Factory New)",
    "M4A1-S | Control Panel (Factory New)",
    "M4A4 | The Battlestar (Factory New)",
    "P2000 | Panther Camo (Minimal Wear)",
    "P250 | Crimson Kimono (Field-Tested)",
    "R8 Revolver | Fade (Factory New)",
    "CZ75-Auto | Distressed (Factory New)",
    "AK-47 | Searing Rage (Minimal Wear)",
    "StatTrak™ Glock-18 | Block-18 (Factory New)",
    "M4A4 | Desert Storm (Minimal Wear)",
    "M4A1-S | Chantico's Fire (Well-Worn)",
    "AWP | Crakow! (Minimal Wear)",
    "CZ75-Auto | Emerald (Factory New)",
    "StatTrak™ UMP-45 | Moonrise (Factory New)",
    "AWP | POP AWP (Minimal Wear)",
    "M4A1-S | Party Animal (Factory New)",
    "SG 553 | Colony IV (Field-Tested)",
    "FAMAS | Djinn (Battle-Scarred)",
    "MP9 | Latte Rush (Field-Tested)",
    "UMP-45 | Exposure (Factory New)",
    "R8 Revolver | Nitro (Factory New)",
    "P90 | Trigon (Field-Tested)",
    "M4A4 | Royal Paladin (Minimal Wear)",
    "UMP-45 | Continuum (Factory New)",
    "MP7 | Whiteout (Field-Tested)",
    "M4A4 | Turbine (Factory New)",
    "StatTrak™ Desert Eagle | Cobalt Disruption (Factory New)",
    "UMP-45 | Fade (Factory New)",
    "Five-SeveN | Hyper Beast (Field-Tested)",
    "StatTrak™ AK-47 | Inheritance (Battle-Scarred)",
    "AK-47 | Frontside Misty (Well-Worn)",
    "Five-SeveN | Retrobution (Factory New)",
    "M4A1-S | Black Lotus (Battle-Scarred)",
    "Desert Eagle | Kumicho Dragon (Battle-Scarred)",
    "AWP | Hyper Beast (Minimal Wear)",
    "M4A1-S | Nightmare (Field-Tested)",
    "M4A1-S | Atomic Alloy (Field-Tested)",
    "M4A4 | Royal Paladin (Factory New)",
    "StatTrak™ Five-SeveN | Copper Galaxy (Factory New)",
    "StatTrak™ Desert Eagle | Cobalt Disruption (Minimal Wear)",
    "StatTrak™ USP-S | Cortex (Well-Worn)",
    "FAMAS | Meltdown (Factory New)",
    "P250 | Bengal Tiger (Minimal Wear)",
    "AUG | Fleet Flock (Minimal Wear)",
    "M4A4 | Griffin (Minimal Wear)",
    "AK-47 | Case Hardened (Minimal Wear)",
    "StatTrak™ USP-S | Cortex (Battle-Scarred)",
    "StatTrak™ AK-47 | Ice Coaled (Minimal Wear)",
    "FAMAS | Styx (Factory New)",
    "Five-SeveN | Case Hardened (Field-Tested)",
    "P2000 | Panther Camo (Field-Tested)",
    "AUG | Fleet Flock (Battle-Scarred)",
    "FAMAS | Dark Water (Minimal Wear)",
    "AWP | Exoskeleton (Field-Tested)",
    "SG 553 | Danger Close (Factory New)",
    "Dual Berettas | Emerald (Factory New)",
    "StatTrak™ SSG 08 | Big Iron (Minimal Wear)",
    "Galil AR | Phoenix Blacklight (Minimal Wear)",
    "StatTrak™ P250 | Asiimov (Field-Tested)",
    "StatTrak™ P90 | Blind Spot (Field-Tested)",
    "StatTrak™ Desert Eagle | Mecha Industries (Field-Tested)",
    "Sawed-Off | Kiss♥Love (Minimal Wear)",
    "AK-47 | Inheritance (Minimal Wear)",
    "Five-SeveN | Fowl Play (Minimal Wear)",
    "StatTrak™ AK-47 | Slate (Minimal Wear)",
    "AWP | Wildfire (Factory New)",
    "Five-SeveN | Case Hardened (Factory New)",
    "AWP | Chrome Cannon (Minimal Wear)",
    "MP9 | Airlock (Factory New)",
    "FAMAS | Pulse (Field-Tested)",
    "AWP | Mortis (Battle-Scarred)",
    "AUG | Radiation Hazard (Field-Tested)",
    "SG 553 | Cyrex (Field-Tested)",
    "Nova | Baroque Orange (Factory New)",
    "StatTrak™ M4A1-S | Dark Water (Minimal Wear)",
    "AWP | Graphite (Factory New)",
    "StatTrak™ MP7 | Just Smile (Factory New)",
    "AK-47 | Nouveau Rouge (Minimal Wear)",
    "StatTrak™ M4A4 | Neo-Noir (Field-Tested)",
    "AWP | Man-o'-war (Minimal Wear)",
    "SSG 08 | Dragonfire (Battle-Scarred)",
    "M4A4 | Turbine (Minimal Wear)",
    "MP7 | Bloodsport (Battle-Scarred)",
    "StatTrak™ M4A4 | Cyber Security (Minimal Wear)",
    "Sawed-Off | Kiss♥Love (Factory New)",
    "M4A4 | 龍王 (Dragon King) (Minimal Wear)",
    "P90 | Ancient Earth (Well-Worn)",
    "AK-47 | Frontside Misty (Minimal Wear)",
    "M4A4 | Urban DDPAT (Factory New)",
    "Five-SeveN | Fowl Play (Factory New)",
    "P250 | Apep's Curse (Minimal Wear)",
    "StatTrak™ Desert Eagle | Kumicho Dragon (Factory New)",
    "Glock-18 | Wasteland Rebel (Field-Tested)",
    "MAG-7 | Monster Call (Factory New)",
    "StatTrak™ FAMAS | Roll Cage (Field-Tested)",
    "StatTrak™ M4A1-S | Decimator (Field-Tested)",
    "USP-S | Cyrex (Factory New)",
    "StatTrak™ AWP | Phobos (Factory New)",
    "MAC-10 | Derailment (Factory New)",
    "R8 Revolver | Skull Crusher (Field-Tested)",
    "AWP | Corticera (Minimal Wear)",
    "StatTrak™ M4A4 | 龍王 (Dragon King) (Minimal Wear)",
    "Galil AR | Urban Rubble (Minimal Wear)",
    "Dual Berettas | Sweet Little Angels (Minimal Wear)",
    "M4A4 | In Living Color (Factory New)",
    "M4A4 | Tornado (Minimal Wear)",
    "StatTrak™ AK-47 | Redline (Field-Tested)",
    "M4A4 | Asiimov (Field-Tested)",
    "StatTrak™ M4A1-S | Cyrex (Minimal Wear)",
    "AK-47 | Bloodsport (Factory New)",
    "USP-S | Whiteout (Battle-Scarred)",
    "USP-S | Kill Confirmed (Factory New)",
    "AUG | Hot Rod (Factory New)",
    "StatTrak™ FAMAS | Commemoration (Minimal Wear)",
    "StatTrak™ AWP | Wildfire (Minimal Wear)",
    "StatTrak™ AWP | Wildfire (Field-Tested)",
    "XM1014 | Banana Leaf (Factory New)",
    "SG 553 | Barricade (Field-Tested)",
    "Nova | Red Quartz (Factory New)",
    "StatTrak™ Glock-18 | Moonrise (Minimal Wear)",
    "Tec-9 | Toxic (Factory New)",
    "AUG | Death by Puppy (Factory New)",
    "StatTrak™ MAC-10 | Disco Tech (Factory New)",
    "StatTrak™ AK-47 | Fuel Injector (Minimal Wear)",
    "StatTrak™ Desert Eagle | Light Rail (Well-Worn)",
    "StatTrak™ Galil AR | Chromatic Aberration (Factory New)",
    "M4A1-S | Stratosphere (Field-Tested)",
    "Glock-18 | Glockingbird (Minimal Wear)",
    "FAMAS | Bad Trip (Minimal Wear)",
    "StatTrak™ AWP | PAW (Minimal Wear)",
    "AK-47 | Breakthrough (Field-Tested)",
    "R8 Revolver | Crazy 8 (Factory New)",
    "StatTrak™ UMP-45 | Wild Child (Field-Tested)",
    "AK-47 | Neon Revolution (Factory New)",
    "Glock-18 | Nuclear Garden (Factory New)",
    "P2000 | Handgun (Factory New)",
    "Glock-18 | AXIA (Minimal Wear)",
    "M4A4 | Global Offensive (Factory New)",
    "StatTrak™ USP-S | Cortex (Factory New)",
    "AWP | Green Energy (Minimal Wear)",
    "StatTrak™ AK-47 | Head Shot (Minimal Wear)",
    "Desert Eagle | Crimson Web (Minimal Wear)",
    "AK-47 | Vulcan (Minimal Wear)",
    "AK-47 | Predator (Minimal Wear)",
    "AWP | Printstream (Factory New)",
    "StatTrak™ AK-47 | Nightwish (Battle-Scarred)",
    "AK-47 | Bloodsport (Well-Worn)",
    "StatTrak™ AK-47 | Asiimov (Field-Tested)",
    "StatTrak™ AK-47 | Vulcan (Field-Tested)",
    "MP9 | Hydra (Field-Tested)",
    "AK-47 | Redline (Battle-Scarred)",
    "SG 553 | Ultraviolet (Minimal Wear)",
    "Five-SeveN | Fairy Tale (Minimal Wear)",
    "StatTrak™ AWP | Redline (Field-Tested)",
    "MP5-SD | Phosphor (Factory New)",
    "StatTrak™ Glock-18 | Neo-Noir (Field-Tested)",
    "StatTrak™ AK-47 | Aquamarine Revenge (Well-Worn)",
    "Desert Eagle | Cobalt Disruption (Factory New)",
    "Desert Eagle | Night (Factory New)",
    "AK-47 | Red Laminate (Field-Tested)",
    "StatTrak™ AK-47 | Ice Coaled (Factory New)",
    "USP-S | Dark Water (Minimal Wear)",
    "FAMAS | Mecha Industries (Field-Tested)",
    "AUG | Chameleon (Field-Tested)",
    "AK-47 | Aquamarine Revenge (Well-Worn)",
    "MAC-10 | Amber Fade (Factory New)",
    "G3SG1 | Stinger (Factory New)",
    "StatTrak™ AWP | Hyper Beast (Minimal Wear)",
    "StatTrak™ AK-47 | Inheritance (Field-Tested)",
    "StatTrak™ AK-47 | Neon Rider (Minimal Wear)",
    "M4A4 | The Emperor (Factory New)",
    "StatTrak™ USP-S | Blueprint (Minimal Wear)",
    "StatTrak™ AK-47 | Neon Revolution (Field-Tested)",
    "CZ75-Auto | Tuxedo (Factory New)",
    "AK-47 | Aquamarine Revenge (Factory New)",
    "StatTrak™ M4A1-S | Vaporwave (Field-Tested)",
    "StatTrak™ UMP-45 | K.O. Factory (Minimal Wear)",
    "StatTrak™ Glock-18 | Shinobu (Field-Tested)",
    "AWP | Chromatic Aberration (Factory New)",
    "AWP | LongDog (Minimal Wear)",
    "MP9 | Hydra (Well-Worn)",
    "P2000 | Acid Etched (Factory New)",
    "AK-47 | The Outsiders (Battle-Scarred)",
    "UMP-45 | Houndstooth (Field-Tested)",
    "StatTrak™ USP-S | Printstream (Field-Tested)",
    "AWP | Asiimov (Well-Worn)",
    "USP-S | Kill Confirmed (Well-Worn)",
    "USP-S | Blueprint (Well-Worn)",
    "StatTrak™ AK-47 | Slate (Well-Worn)",
    "Negev | Nuclear Waste (Minimal Wear)",
    "Desert Eagle | Printstream (Factory New)",
    "StatTrak™ Desert Eagle | Mecha Industries (Factory New)",
    "MAC-10 | Surfwood (Minimal Wear)",
    "StatTrak™ M4A4 | Hellfire (Factory New)",
    "StatTrak™ AK-47 | Slate (Battle-Scarred)",
    "UMP-45 | Crime Scene (Factory New)",
    "MP5-SD | Condition Zero (Factory New)",
    "AUG | Chameleon (Minimal Wear)",
    "SG 553 | Desert Blossom (Minimal Wear)",
    "StatTrak™ Desert Eagle | Printstream (Factory New)",
    "StatTrak™ Five-SeveN | Case Hardened (Factory New)",
    "USP-S | Printstream (Well-Worn)",
    "P90 | Trigon (Minimal Wear)",
    "StatTrak™ M4A1-S | Vaporwave (Minimal Wear)",
    "FAMAS | Mecha Industries (Factory New)",
    "StatTrak™ USP-S | Kill Confirmed (Minimal Wear)",
    "Glock-18 | Wasteland Rebel (Minimal Wear)",
    "StatTrak™ AWP | Phobos (Minimal Wear)",
    "StatTrak™ M4A4 | Turbine (Factory New)",
    "P250 | Mehndi (Field-Tested)",
    "FAMAS | Bad Trip (Battle-Scarred)",
    "M4A1-S | Guardian (Field-Tested)",
    "AUG | Anodized Navy (Factory New)",
    "P90 | Storm (Minimal Wear)",
    "StatTrak™ Glock-18 | Vogue (Factory New)",
    "StatTrak™ M4A1-S | Basilisk (Field-Tested)",
    "StatTrak™ AK-47 | Uncharted (Minimal Wear)",
    "MP7 | Whiteout (Minimal Wear)",
    "AK-47 | Neon Rider (Minimal Wear)",
    "StatTrak™ Glock-18 | Gold Toof (Minimal Wear)",
    "MP9 | Hot Rod (Factory New)",
    "AK-47 | Legion of Anubis (Factory New)",
    "Glock-18 | Synth Leaf (Factory New)",
    "StatTrak™ AWP | Electric Hive (Minimal Wear)",
    "AWP | Containment Breach (Battle-Scarred)",
    "P250 | Bengal Tiger (Field-Tested)",
    "Desert Eagle | Fennec Fox (Minimal Wear)",
    "AWP | Printstream (Battle-Scarred)",
    "AWP | Elite Build (Battle-Scarred)",
    "StatTrak™ M4A1-S | Player Two (Factory New)",
    "SG 553 | Phantom (Factory New)",
    "StatTrak™ USP-S | Printstream (Battle-Scarred)",
    "UMP-45 | Wild Child (Well-Worn)",
    "AUG | Wings (Minimal Wear)",
    "StatTrak™ AK-47 | Neon Rider (Factory New)",
    "G3SG1 | Keeping Tabs (Factory New)",
    "USP-S | The Traitor (Minimal Wear)",
    "M4A4 | X-Ray (Minimal Wear)",
    "Tec-9 | Whiteout (Well-Worn)",
    "StatTrak™ AWP | Atheris (Field-Tested)",
    "Tec-9 | Bamboo Forest (Factory New)",
    "AUG | Lil' Pig (Factory New)",
    "AWP | Fever Dream (Minimal Wear)",
    "AK-47 | Case Hardened (Well-Worn)",
    "StatTrak™ AWP | Queen's Gambit (Battle-Scarred)",
    "StatTrak™ UMP-45 | Momentum (Minimal Wear)",
    "AK-47 | Inheritance (Well-Worn)",
    "USP-S | Printstream (Factory New)",
    "MP7 | Smoking Kills (Well-Worn)",
    "StatTrak™ Galil AR | Control (Factory New)",
    "StatTrak™ MP9 | Food Chain (Factory New)",
    "USP-S | Target Acquired (Minimal Wear)",
    "Glock-18 | Water Elemental (Well-Worn)",
    "StatTrak™ M4A1-S | Chantico's Fire (Minimal Wear)",
    "Tec-9 | Orange Murano (Factory New)",
    "AWP | CMYK (Battle-Scarred)",
    "P250 | Whiteout (Field-Tested)",
    "Desert Eagle | Firebreathing (Factory New)",
    "CZ75-Auto | Slalom (Minimal Wear)",
    "StatTrak™ AUG | Stymphalian (Minimal Wear)",
    "Glock-18 | Groundwater (Minimal Wear)",
    "P90 | ScaraB Rush (Field-Tested)",
    "M4A4 | 龍王 (Dragon King) (Factory New)",
    "AK-47 | Cartel (Field-Tested)",
    "AK-47 | Neon Revolution (Well-Worn)",
    "StatTrak™ AWP | Oni Taiji (Field-Tested)",
    "M4A1-S | Cyrex (Factory New)",
    "StatTrak™ AK-47 | The Oligarch (Minimal Wear)",
    "StatTrak™ M4A4 | Temukau (Minimal Wear)",
    "XM1014 | Teclu Burner (Factory New)",
    "StatTrak™ M4A4 | Evil Daimyo (Field-Tested)",
    "MAC-10 | Toybox (Field-Tested)",
    "P250 | Dark Filigree (Field-Tested)",
    "Galil AR | Rainbow Spoon (Minimal Wear)",
    "AWP | Elite Build (Field-Tested)",
    "USP-S | Orange Anolis (Factory New)",
    "USP-S | Royal Blue (Field-Tested)",
    "XM1014 | XOXO (Battle-Scarred)",
    "StatTrak™ M4A4 | Magnesium (Minimal Wear)",
    "StatTrak™ P250 | Epicenter (Minimal Wear)",
    "Desert Eagle | Mulberry (Field-Tested)",
    "Negev | Phoenix Stencil (Factory New)",
    "StatTrak™ AK-47 | Inheritance (Well-Worn)",
    "StatTrak™ AK-47 | Cartel (Field-Tested)",
    "M4A1-S | Glitched Paint (Well-Worn)",
    "M4A4 | Desert Storm (Field-Tested)",
    "AWP | Oni Taiji (Field-Tested)",
    "Glock-18 | Glockingbird (Factory New)",
    "Nova | Green Apple (Factory New)",
    "Glock-18 | Water Elemental (Battle-Scarred)",
    "MP7 | Amberline (Factory New)",
    "AWP | Crakow! (Field-Tested)",
    "Tec-9 | Hades (Factory New)",
    "StatTrak™ M4A4 | In Living Color (Field-Tested)",
    "P90 | ScaraB Rush (Minimal Wear)",
    "StatTrak™ Desert Eagle | Kumicho Dragon (Minimal Wear)",
    "AWP | LongDog (Well-Worn)",
    "Glock-18 | Snack Attack (Well-Worn)",
    "StatTrak™ AK-47 | Neon Revolution (Factory New)",
    "M4A4 | Polysoup (Factory New)",
    "AUG | Eye of Zapems (Field-Tested)",
    "P250 | Cartel (Minimal Wear)",
    "Desert Eagle | Starcade (Field-Tested)",
    "M4A4 | Full Throttle (Field-Tested)",
    "Desert Eagle | Kumicho Dragon (Minimal Wear)",
    "StatTrak™ UMP-45 | Momentum (Field-Tested)",
    "StatTrak™ FAMAS | Eye of Athena (Minimal Wear)",
    "AK-47 | Neon Revolution (Battle-Scarred)",
    "Tec-9 | Bamboo Forest (Field-Tested)",
    "SCAR-20 | Wild Berry (Factory New)",
    "StatTrak™ AWP | Neo-Noir (Factory New)",
    "USP-S | Overgrowth (Factory New)",
    "Glock-18 | Bullet Queen (Well-Worn)",
    "StatTrak™ Desert Eagle | Printstream (Field-Tested)",
    "MP7 | Nemesis (Minimal Wear)",
    "Galil AR | Sugar Rush (Factory New)",
    "StatTrak™ Dual Berettas | Melondrama (Factory New)",
    "M4A4 | In Living Color (Well-Worn)",
    "M4A1-S | Control Panel (Well-Worn)",
    "StatTrak™ Nova | Gila (Factory New)",
    "Desert Eagle | Heirloom (Minimal Wear)",
    "StatTrak™ M4A1-S | Mecha Industries (Minimal Wear)",
    "StatTrak™ P250 | Wingshot (Minimal Wear)",
    "FAMAS | Pulse (Minimal Wear)",
    "StatTrak™ M4A1-S | Golden Coil (Minimal Wear)",
    "USP-S | Neo-Noir (Minimal Wear)",
    "P250 | Nuclear Threat (Field-Tested)",
    "AK-47 | Orbit Mk01 (Field-Tested)",
    "StatTrak™ AWP | Chrome Cannon (Factory New)",
    "M4A4 | Buzz Kill (Battle-Scarred)",
    "MP7 | Just Smile (Factory New)",
    "StatTrak™ AK-47 | Frontside Misty (Well-Worn)",
    "AWP | Neo-Noir (Factory New)",
    "StatTrak™ USP-S | Blueprint (Field-Tested)",
    "StatTrak™ FAMAS | Rapid Eye Movement (Well-Worn)",
    "StatTrak™ Glock-18 | Gold Toof (Field-Tested)",
    "P2000 | Dispatch (Minimal Wear)",
    "MAC-10 | Toybox (Minimal Wear)",
    "StatTrak™ AK-47 | Neon Rider (Field-Tested)",
    "Nova | Sobek's Bite (Field-Tested)",
    "M4A4 | Hellish (Well-Worn)",
    "StatTrak™ AWP | Fever Dream (Field-Tested)",
    "M4A4 | Desolate Space (Battle-Scarred)",
    "StatTrak™ P90 | Shallow Grave (Factory New)",
    "M4A4 | Buzz Kill (Minimal Wear)",
    "StatTrak™ AWP | Printstream (Battle-Scarred)",
    "UMP-45 | Metal Flowers (Factory New)",
    "StatTrak™ AK-47 | The Outsiders (Field-Tested)",
    "Five-SeveN | Heat Treated (Battle-Scarred)",
    "XM1014 | Halftone Shift (Factory New)",
    "P2000 | Imperial Dragon (Minimal Wear)",
    "AK-47 | Orbit Mk01 (Minimal Wear)",
    "M4A4 | Faded Zebra (Battle-Scarred)",
    "SCAR-20 | Cardiac (Field-Tested)",
    "MAC-10 | Propaganda (Minimal Wear)",
    "MAC-10 | Red Filigree (Factory New)",
    "M4A1-S | Dark Water (Field-Tested)",
    "FAMAS | Sergeant (Minimal Wear)",
    "FAMAS | Roll Cage (Factory New)",
    "MAC-10 | Disco Tech (Minimal Wear)",
    "StatTrak™ CZ75-Auto | Victoria (Field-Tested)",
    "M4A4 | 龍王 (Dragon King) (Field-Tested)",
    "MAG-7 | Core Breach (Factory New)",
    "SCAR-20 | Bloodsport (Factory New)",
    "Glock-18 | Ramese's Reach (Minimal Wear)",
    "SSG 08 | Death's Head (Field-Tested)",
    "StatTrak™ Galil AR | Chromatic Aberration (Minimal Wear)",
    "StatTrak™ M4A1-S | Printstream (Battle-Scarred)",
    "USP-S | Para Green (Field-Tested)",
    "M4A4 | In Living Color (Minimal Wear)",
    "StatTrak™ AK-47 | Case Hardened (Well-Worn)",
    "P250 | Whiteout (Factory New)",
    "Sawed-Off | Kiss♥Love (Well-Worn)",
    "MP9 | Pandora's Box (Factory New)",
    "StatTrak™ P250 | Muertos (Minimal Wear)",
    "StatTrak™ AWP | Wildfire (Factory New)",
    "M4A4 | Buzz Kill (Well-Worn)",
    "AWP | Worm God (Factory New)",
    "StatTrak™ P90 | Shallow Grave (Field-Tested)",
    "Tec-9 | Remote Control (Minimal Wear)",
    "StatTrak™ M4A1-S | Leaded Glass (Battle-Scarred)",
    "P90 | Chopper (Factory New)",
    "FAMAS | Bad Trip (Factory New)",
    "P90 | Attack Vector (Field-Tested)",
    "StatTrak™ AK-47 | Phantom Disruptor (Factory New)",
    "Glock-18 | Royal Legion (Minimal Wear)",
    "Desert Eagle | Ocean Drive (Minimal Wear)",
    "USP-S | Monster Mashup (Field-Tested)",
    "M4A1-S | Golden Coil (Factory New)",
    "AWP | Sun in Leo (Field-Tested)",
    "StatTrak™ AK-47 | Redline (Minimal Wear)",
    "StatTrak™ AWP | PAW (Factory New)",
    "MAC-10 | Heat (Field-Tested)",
    "Five-SeveN | Hyper Beast (Minimal Wear)",
    "MP7 | Fade (Minimal Wear)",
    "CZ75-Auto | Victoria (Field-Tested)",
    "M4A1-S | Mecha Industries (Minimal Wear)",
    "AK-47 | The Oligarch (Factory New)",
    "P90 | Module (Factory New)",
    "StatTrak™ Dual Berettas | Melondrama (Battle-Scarred)",
    "StatTrak™ SSG 08 | Memorial (Factory New)",
    "StatTrak™ AWP | Atheris (Factory New)",
    "Five-SeveN | Boost Protocol (Minimal Wear)",
    "StatTrak™ P250 | Asiimov (Battle-Scarred)",
    "Glock-18 | Mirror Mosaic (Field-Tested)",
    "AK-47 | Frontside Misty (Battle-Scarred)",
    "MP7 | Army Recon (Factory New)",
    "M4A4 | X-Ray (Factory New)",
    "Desert Eagle | Code Red (Factory New)",
    "SSG 08 | Fever Dream (Factory New)",
    "StatTrak™ Galil AR | Chromatic Aberration (Battle-Scarred)",
    "MP9 | Setting Sun (Factory New)",
    "Galil AR | Phoenix Blacklight (Field-Tested)",
    "Desert Eagle | Firebreathing (Minimal Wear)",
    "StatTrak™ MP7 | Ocean Foam (Factory New)",
    "M4A4 | Tooth Fairy (Battle-Scarred)",
    "Tec-9 | Decimator (Minimal Wear)",
    "StatTrak™ AWP | Fever Dream (Minimal Wear)",
    "USP-S | Para Green (Minimal Wear)",
    "AWP | The End (Factory New)",
    "StatTrak™ M4A4 | Desolate Space (Field-Tested)",
    "SSG 08 | Dark Water (Field-Tested)",
    "StatTrak™ USP-S | Cyrex (Field-Tested)",
    "StatTrak™ M4A1-S | Blood Tiger (Factory New)",
    "AK-47 | Steel Delta (Minimal Wear)",
    "Nova | Rising Skull (Minimal Wear)",
    "AWP | Wildfire (Battle-Scarred)",
    "Dual Berettas | Royal Consorts (Well-Worn)",
    "Desert Eagle | Midnight Storm (Minimal Wear)",
    "StatTrak™ AK-47 | Case Hardened (Battle-Scarred)",
    "M4A1-S | Vaporwave (Minimal Wear)",
    "UMP-45 | K.O. Factory (Factory New)",
    "Nova | Rising Skull (Field-Tested)",
    "StatTrak™ AWP | Hyper Beast (Factory New)",
    "AWP | Ice Coaled (Factory New)",
    "AK-47 | Emerald Pinstripe (Well-Worn)",
    "USP-S | Ancient Visions (Factory New)",
    "StatTrak™ FAMAS | Rapid Eye Movement (Factory New)",
    "StatTrak™ M4A4 | 龍王 (Dragon King) (Field-Tested)",
    "CZ75-Auto | Xiangliu (Factory New)",
    "StatTrak™ AK-47 | Legion of Anubis (Factory New)",
    "Glock-18 | Snack Attack (Minimal Wear)",
    "SSG 08 | Big Iron (Minimal Wear)",
    "SSG 08 | Parallax (Minimal Wear)",
    "Dual Berettas | Sweet Little Angels (Factory New)",
    "Five-SeveN | Case Hardened (Well-Worn)",
    "AWP | Oni Taiji (Minimal Wear)",
    "AUG | Flame Jörmungandr (Factory New)",
    "MP9 | Music Box (Field-Tested)",
    "StatTrak™ M4A4 | Desolate Space (Well-Worn)",
    "AK-47 | Head Shot (Factory New)",
    "StatTrak™ AWP | Mortis (Battle-Scarred)",
    "StatTrak™ Desert Eagle | Mecha Industries (Minimal Wear)",
    "AK-47 | Cartel (Battle-Scarred)",
    "UMP-45 | Crimson Foil (Battle-Scarred)",
    "StatTrak™ AK-47 | Nightwish (Well-Worn)",
    "AUG | Carved Jade (Minimal Wear)",
    "StatTrak™ M4A1-S | Decimator (Factory New)",
    "StatTrak™ M4A4 | Evil Daimyo (Minimal Wear)",
    "StatTrak™ M4A1-S | Golden Coil (Field-Tested)",
    "MP9 | Food Chain (Factory New)",
    "AK-47 | Green Laminate (Minimal Wear)",
    "USP-S | Purple DDPAT (Field-Tested)",
    "AK-47 | Neon Rider (Battle-Scarred)",
    "XM1014 | XOXO (Factory New)",
    "MP9 | Goo (Factory New)",
    "StatTrak™ M4A1-S | Chantico's Fire (Field-Tested)",
    "StatTrak™ AK-47 | The Outsiders (Factory New)",
    "USP-S | The Traitor (Battle-Scarred)",
    "P90 | Leather (Factory New)",
    "Galil AR | Cerberus (Well-Worn)",
    "AK-47 | Crane Flight (Minimal Wear)",
    "SG 553 | Pulse (Minimal Wear)",
    "M4A4 | The Emperor (Minimal Wear)",
    "StatTrak™ USP-S | Guardian (Minimal Wear)",
    "FAMAS | Prime Conspiracy (Factory New)",
    "Glock-18 | Reactor (Field-Tested)",
    "MAC-10 | Case Hardened (Field-Tested)",
    "G3SG1 | Murky (Factory New)",
    "Five-SeveN | Fowl Play (Battle-Scarred)",
    "P90 | Death by Kitty (Field-Tested)",
    "AUG | Stymphalian (Factory New)",
    "USP-S | Orion (Minimal Wear)",
    "StatTrak™ AK-47 | Asiimov (Minimal Wear)",
    "StatTrak™ USP-S | Blood Tiger (Factory New)",
    "StatTrak™ M4A4 | Griffin (Field-Tested)",
    "Five-SeveN | Hyper Beast (Well-Worn)",
    "StatTrak™ AWP | Atheris (Well-Worn)",
    "StatTrak™ AK-47 | Frontside Misty (Field-Tested)",
    "M4A4 | In Living Color (Battle-Scarred)",
    "StatTrak™ AK-47 | Frontside Misty (Minimal Wear)",
    "StatTrak™ AK-47 | Head Shot (Field-Tested)",
    "M4A1-S | Blood Tiger (Minimal Wear)",
    "P2000 | Imperial Dragon (Battle-Scarred)",
    "M4A4 | Cyber Security (Field-Tested)",
    "USP-S | Jawbreaker (Minimal Wear)",
    "AK-47 | Leet Museo (Minimal Wear)",
    "StatTrak™ SSG 08 | Dragonfire (Factory New)",
    "StatTrak™ P250 | Mehndi (Field-Tested)",
    "StatTrak™ Glock-18 | Moonrise (Factory New)",
    "StatTrak™ USP-S | Torque (Factory New)",
    "AWP | The End (Minimal Wear)",
    "FAMAS | Eye of Athena (Minimal Wear)",
    "UMP-45 | Neo-Noir (Field-Tested)",
    "Five-SeveN | Case Hardened (Battle-Scarred)",
    "Five-SeveN | Monkey Business (Well-Worn)",
    "Glock-18 | AXIA (Battle-Scarred)",
    "MAC-10 | Disco Tech (Factory New)",
    "USP-S | Stainless (Minimal Wear)",
    "P250 | Bengal Tiger (Factory New)",
    "MP7 | Powercore (Minimal Wear)",
    "StatTrak™ AK-47 | The Outsiders (Battle-Scarred)",
    "MAG-7 | Praetorian (Factory New)",
    "Desert Eagle | Code Red (Well-Worn)",
    "StatTrak™ Desert Eagle | Crimson Web (Factory New)",
    "AUG | Navy Murano (Well-Worn)",
    "StatTrak™ AUG | Chameleon (Minimal Wear)",
    "G3SG1 | Flux (Field-Tested)",
    "PP-Bizon | Bamboo Print (Field-Tested)",
    "Galil AR | Chromatic Aberration (Battle-Scarred)",
    "Dual Berettas | Cobra Strike (Factory New)",
    "StatTrak™ P250 | Visions (Battle-Scarred)",
]
