# Auto-generated from risk analysis notebook
# SOURCE_CSV = 'C:\\Roman\\skins_roundtrip_v1\\skin_homog\\screener_preprocess_risk\\risk_metrics.csv'
# OUTPUT_LIST = 'C:\\Roman\\skins_roundtrip_v1\\lists\\skins_normal_filtered2.py'
# mask_ema: ema_gap>=-0.01 & slope>=-0.002 OR (ema is null & ret_7d>=0.01 & slope>=0.0)
# mask_trend: ret_7d>=-0.02 & slope>=-0.003 OR ret_7d>=0.01 & slope>=-0.005
# mask_price_risk: downside_14d<=0.12 OR (downside_14d<=0.18 & range_14d<=0.22)
# mask_liquidity: steam_sales_7d_n>=40 & steam_turnover_proxy>=0.9
# mask_tail: tail_ratio>=0.90 OR (tail_ratio>=0.88 & downside_risk<=8)
# N_OUTPUT_ITEMS = 265

ITEMS = [
    'Desert Eagle | Calligraffiti (Factory New)',
    'Galil AR | Black Sand (Factory New)',
    'P2000 | Urban Hazard (Factory New)',
    'SSG 08 | Ghost Crusader (Factory New)',
    'AK-47 | Head Shot (Field-Tested)',
    'XM1014 | Entombed (Minimal Wear)',
    'AUG | Syd Mead (Field-Tested)',
    'AK-47 | Nightwish (Battle-Scarred)',
    'P2000 | Imperial Dragon (Field-Tested)',
    'Negev | dev_texture (Factory New)',
    'Glock-18 | Steel Disruption (Factory New)',
    'M4A4 | The Emperor (Field-Tested)',
    'UMP-45 | Momentum (Field-Tested)',
    'AWP | Hyper Beast (Battle-Scarred)',
    'P250 | Visions (Minimal Wear)',
    'AK-47 | Baroque Purple (Field-Tested)',
    'G3SG1 | Stinger (Field-Tested)',
    'CZ75-Auto | Red Astor (Factory New)',
    'M4A4 | Neo-Noir (Field-Tested)',
    'AUG | Stymphalian (Field-Tested)',
    'M4A4 | Temukau (Field-Tested)',
    'Glock-18 | Mirror Mosaic (Battle-Scarred)',
    'AWP | Asiimov (Battle-Scarred)',
    'M4A4 | Royal Paladin (Field-Tested)',
    'Desert Eagle | Urban DDPAT (Minimal Wear)',
    'Glock-18 | Gold Toof (Field-Tested)',
    'Sawed-Off | Devourer (Field-Tested)',
    'Five-SeveN | Angry Mob (Field-Tested)',
    'AK-47 | Asiimov (Field-Tested)',
    'CZ75-Auto | Slalom (Factory New)',
    'AUG | Syd Mead (Minimal Wear)',
    'Five-SeveN | Case Hardened (Minimal Wear)',
    'P90 | Nostalgia (Field-Tested)',
    'M4A1-S | Leaded Glass (Field-Tested)',
    'MP7 | Fade (Factory New)',
    'UMP-45 | Wild Child (Battle-Scarred)',
    'AK-47 | Nightwish (Field-Tested)',
    'AUG | Momentum (Field-Tested)',
    'P250 | Vino Primo (Minimal Wear)',
    'Desert Eagle | Mulberry (Minimal Wear)',
    'Desert Eagle | Ocean Drive (Field-Tested)',
    'M4A1-S | Control Panel (Field-Tested)',
    'SSG 08 | Detour (Factory New)',
    'M249 | Jungle (Field-Tested)',
    'M4A4 | In Living Color (Field-Tested)',
    'Five-SeveN | Fowl Play (Field-Tested)',
    'AK-47 | Cartel (Factory New)',
    'MP9 | Hydra (Minimal Wear)',
    'USP-S | Cortex (Minimal Wear)',
    'FAMAS | Commemoration (Field-Tested)',
    'AK-47 | Legion of Anubis (Field-Tested)',
    'M4A1-S | Vaporwave (Battle-Scarred)',
    'M4A1-S | Leaded Glass (Minimal Wear)',
    'M4A4 | Tooth Fairy (Minimal Wear)',
    'AWP | Exoskeleton (Battle-Scarred)',
    'Dual Berettas | Royal Consorts (Field-Tested)',
    'AK-47 | Head Shot (Battle-Scarred)',
    'P90 | Shallow Grave (Minimal Wear)',
    'Tec-9 | Fuel Injector (Field-Tested)',
    'Five-SeveN | Boost Protocol (Factory New)',
    'AWP | Ice Coaled (Well-Worn)',
    'Glock-18 | Water Elemental (Field-Tested)',
    'Desert Eagle | Night (Minimal Wear)',
    'FAMAS | Yeti Camo (Factory New)',
    'AK-47 | Nouveau Rouge (Battle-Scarred)',
    'CZ75-Auto | Slalom (Field-Tested)',
    'R8 Revolver | Fade (Field-Tested)',
    'AK-47 | Emerald Pinstripe (Field-Tested)',
    'G3SG1 | Dream Glade (Factory New)',
    'Glock-18 | Vogue (Field-Tested)',
    'Desert Eagle | Crimson Web (Field-Tested)',
    'USP-S | Cyrex (Minimal Wear)',
    'AK-47 | Crossfade (Minimal Wear)',
    'AWP | Fever Dream (Field-Tested)',
    'M4A4 | Tooth Fairy (Field-Tested)',
    'Five-SeveN | Monkey Business (Minimal Wear)',
    'AK-47 | Nightwish (Well-Worn)',
    'Glock-18 | AXIA (Field-Tested)',
    'MP9 | Airlock (Field-Tested)',
    'Desert Eagle | Printstream (Field-Tested)',
    'USP-S | Overgrowth (Field-Tested)',
    'AK-47 | Legion of Anubis (Minimal Wear)',
    'Desert Eagle | Conspiracy (Minimal Wear)',
    'CZ75-Auto | Army Sheen (Minimal Wear)',
    'P90 | Nostalgia (Minimal Wear)',
    'AK-47 | Slate (Minimal Wear)',
    'AWP | Ice Coaled (Battle-Scarred)',
    'AK-47 | Redline (Field-Tested)',
    'P2000 | Wicked Sick (Well-Worn)',
    'FAMAS | Mecha Industries (Minimal Wear)',
    'Sawed-Off | Wasteland Princess (Minimal Wear)',
    'MP9 | Starlight Protector (Battle-Scarred)',
    'AK-47 | Phantom Disruptor (Battle-Scarred)',
    'Glock-18 | Gold Toof (Minimal Wear)',
    'AK-47 | Slate (Battle-Scarred)',
    'AK-47 | Rat Rod (Field-Tested)',
    'Galil AR | Rainbow Spoon (Factory New)',
    'MAC-10 | Stalker (Minimal Wear)',
    'M4A4 | Hellish (Battle-Scarred)',
    'AWP | Hyper Beast (Field-Tested)',
    'P90 | Shallow Grave (Field-Tested)',
    'Desert Eagle | Mecha Industries (Minimal Wear)',
    'Galil AR | Eco (Field-Tested)',
    'Five-SeveN | Heat Treated (Field-Tested)',
    'M4A1-S | Flashback (Minimal Wear)',
    'AK-47 | Aquamarine Revenge (Minimal Wear)',
    'AK-47 | Ice Coaled (Field-Tested)',
    'AK-47 | Slate (Well-Worn)',
    'Glock-18 | Block-18 (Factory New)',
    'AK-47 | Phantom Disruptor (Field-Tested)',
    'MP9 | Arctic Tri-Tone (Field-Tested)',
    'Glock-18 | Vogue (Minimal Wear)',
    'USP-S | Cyrex (Field-Tested)',
    'AK-47 | Point Disarray (Field-Tested)',
    'FAMAS | Bad Trip (Field-Tested)',
    'M4A1-S | Decimator (Field-Tested)',
    'FAMAS | Bad Trip (Well-Worn)',
    'USP-S | Black Lotus (Minimal Wear)',
    'Five-SeveN | Heat Treated (Minimal Wear)',
    'UMP-45 | Crimson Foil (Factory New)',
    'M4A1-S | Flashback (Well-Worn)',
    'M4A1-S | Basilisk (Minimal Wear)',
    'USP-S | The Traitor (Field-Tested)',
    'USP-S | Blueprint (Field-Tested)',
    'M4A1-S | Player Two (Battle-Scarred)',
    'AWP | Wildfire (Field-Tested)',
    'M4A4 | Polysoup (Field-Tested)',
    'M4A1-S | Golden Coil (Field-Tested)',
    'AK-47 | Nightwish (Minimal Wear)',
    'Desert Eagle | Kumicho Dragon (Battle-Scarred)',
    'XM1014 | Entombed (Factory New)',
    'USP-S | Printstream (Minimal Wear)',
    'Desert Eagle | Conspiracy (Field-Tested)',
    'PP-Bizon | High Roller (Minimal Wear)',
    'AK-47 | Wasteland Rebel (Field-Tested)',
    'AWP | POP AWP (Field-Tested)',
    'AWP | Atheris (Minimal Wear)',
    'MP9 | Food Chain (Field-Tested)',
    'M4A1-S | Flashback (Field-Tested)',
    'MP7 | Bloodsport (Field-Tested)',
    'Five-SeveN | Heat Treated (Well-Worn)',
    'SG 553 | Dragon Tech (Factory New)',
    'USP-S | Kill Confirmed (Field-Tested)',
    'AK-47 | Blue Laminate (Minimal Wear)',
    'FAMAS | Styx (Field-Tested)',
    'Desert Eagle | Code Red (Minimal Wear)',
    'AK-47 | Aphrodite (Minimal Wear)',
    'Galil AR | Rainbow Spoon (Field-Tested)',
    'AK-47 | Point Disarray (Minimal Wear)',
    'P250 | Epicenter (Field-Tested)',
    'USP-S | Whiteout (Battle-Scarred)',
    'USP-S | Black Lotus (Factory New)',
    'USP-S | Guardian (Minimal Wear)',
    'XM1014 | Ziggy (Factory New)',
    'AWP | PAW (Minimal Wear)',
    'MP9 | Mount Fuji (Field-Tested)',
    'AK-47 | Neon Rider (Field-Tested)',
    'M4A1-S | Decimator (Battle-Scarred)',
    'MP9 | Arctic Tri-Tone (Factory New)',
    'UMP-45 | Crimson Foil (Field-Tested)',
    'Nova | Antique (Factory New)',
    'Dual Berettas | Royal Consorts (Minimal Wear)',
    'Glock-18 | Water Elemental (Minimal Wear)',
    'AWP | Green Energy (Minimal Wear)',
    'AWP | Hyper Beast (Well-Worn)',
    'CZ75-Auto | Syndicate (Field-Tested)',
    'MP9 | Food Chain (Well-Worn)',
    'UMP-45 | Neo-Noir (Well-Worn)',
    'M4A4 | Full Throttle (Battle-Scarred)',
    'USP-S | Whiteout (Field-Tested)',
    'Galil AR | Chromatic Aberration (Well-Worn)',
    'Galil AR | Tornado (Field-Tested)',
    'AK-47 | Point Disarray (Battle-Scarred)',
    'M4A1-S | Black Lotus (Minimal Wear)',
    'AK-47 | Legion of Anubis (Battle-Scarred)',
    'Desert Eagle | Printstream (Minimal Wear)',
    'AK-47 | Frontside Misty (Well-Worn)',
    'USP-S | Printstream (Battle-Scarred)',
    'SSG 08 | Bloodshot (Field-Tested)',
    'M4A4 | Evil Daimyo (Field-Tested)',
    'AUG | Fleet Flock (Minimal Wear)',
    'AWP | Redline (Field-Tested)',
    'AK-47 | The Oligarch (Battle-Scarred)',
    'Desert Eagle | Kumicho Dragon (Field-Tested)',
    'USP-S | Alpine Camo (Factory New)',
    'FAMAS | Pulse (Field-Tested)',
    'USP-S | Royal Blue (Field-Tested)',
    'USP-S | Purple DDPAT (Field-Tested)',
    'AWP | Atheris (Field-Tested)',
    'AK-47 | Cartel (Minimal Wear)',
    'P90 | Trigon (Field-Tested)',
    'AWP | Chrome Cannon (Well-Worn)',
    'Five-SeveN | Case Hardened (Battle-Scarred)',
    'MP9 | Arctic Tri-Tone (Battle-Scarred)',
    'M4A4 | Spider Lily (Field-Tested)',
    'AWP | Asiimov (Well-Worn)',
    'AWP | Containment Breach (Battle-Scarred)',
    'AK-47 | Elite Build (Minimal Wear)',
    "Nova | Sobek's Bite (Field-Tested)",
    'M4A4 | 龍王 (Dragon King) (Minimal Wear)',
    'M4A1-S | Nightmare (Field-Tested)',
    'AWP | Exoskeleton (Field-Tested)',
    'AK-47 | Frontside Misty (Minimal Wear)',
    'USP-S | Printstream (Well-Worn)',
    'UMP-45 | Crimson Foil (Battle-Scarred)',
    'MP7 | Powercore (Minimal Wear)',
    'USP-S | Kill Confirmed (Well-Worn)',
    'Five-SeveN | Fowl Play (Minimal Wear)',
    'AK-47 | Inheritance (Minimal Wear)',
    'Glock-18 | Water Elemental (Well-Worn)',
    'USP-S | The Traitor (Minimal Wear)',
    'AK-47 | Nouveau Rouge (Minimal Wear)',
    'SSG 08 | Parallax (Minimal Wear)',
    'Tec-9 | Bamboo Forest (Factory New)',
    'MP9 | Hydra (Field-Tested)',
    'AK-47 | Redline (Battle-Scarred)',
    'FAMAS | Mecha Industries (Field-Tested)',
    'FAMAS | Pulse (Minimal Wear)',
    'M4A4 | Desolate Space (Battle-Scarred)',
    'Desert Eagle | Crimson Web (Minimal Wear)',
    'Glock-18 | Nuclear Garden (Factory New)',
    'Five-SeveN | Heat Treated (Battle-Scarred)',
    'M4A1-S | Guardian (Field-Tested)',
    'FAMAS | Mecha Industries (Factory New)',
    'AWP | Elite Build (Battle-Scarred)',
    'AUG | Chameleon (Minimal Wear)',
    'Desert Eagle | Printstream (Factory New)',
    'P90 | Storm (Minimal Wear)',
    'Five-SeveN | Boost Protocol (Minimal Wear)',
    'SCAR-20 | Wild Berry (Factory New)',
    'Galil AR | Rainbow Spoon (Minimal Wear)',
    'AUG | Fleet Flock (Battle-Scarred)',
    'M4A4 | Polysoup (Factory New)',
    'XM1014 | Halftone Shift (Factory New)',
    'Glock-18 | AXIA (Minimal Wear)',
    'M4A1-S | Glitched Paint (Well-Worn)',
    'M4A4 | In Living Color (Battle-Scarred)',
    'Desert Eagle | Kumicho Dragon (Minimal Wear)',
    'Glock-18 | Snack Attack (Minimal Wear)',
    'SSG 08 | Dark Water (Field-Tested)',
    'M4A4 | 龍王 (Dragon King) (Field-Tested)',
    'Glock-18 | Water Elemental (Battle-Scarred)',
    'AK-47 | Orbit Mk01 (Field-Tested)',
    'AK-47 | Neon Rider (Minimal Wear)',
    'USP-S | Monster Mashup (Field-Tested)',
    'AWP | Printstream (Battle-Scarred)',
    'AK-47 | Orbit Mk01 (Minimal Wear)',
    'Five-SeveN | Monkey Business (Well-Worn)',
    'AK-47 | Steel Delta (Minimal Wear)',
    'AK-47 | Frontside Misty (Battle-Scarred)',
    'AWP | Ice Coaled (Factory New)',
    'USP-S | Jawbreaker (Minimal Wear)',
    'SSG 08 | Big Iron (Minimal Wear)',
    'USP-S | The Traitor (Battle-Scarred)',
    'SCAR-20 | Bloodsport (Factory New)',
    'Desert Eagle | Midnight Storm (Minimal Wear)',
    'M4A4 | The Emperor (Minimal Wear)',
    'P2000 | Imperial Dragon (Battle-Scarred)',
    'Desert Eagle | Code Red (Well-Worn)',
    'SCAR-20 | Cardiac (Field-Tested)',
    'UMP-45 | Neo-Noir (Field-Tested)',
    'AWP | Sun in Leo (Field-Tested)',
    'Nova | Rising Skull (Field-Tested)',
    'AK-47 | Neon Rider (Battle-Scarred)',
    'Glock-18 | AXIA (Battle-Scarred)',
]
