# Auto-generated 30% sample from lists/skins_normal_filtered1.py
# RANDOM_SEED = 20260427
# SOURCE_ITEMS = 1124
# SAMPLE_ITEMS = 337

ITEMS = [
    "AK-47 | Aquamarine Revenge (Minimal Wear)",
    "AK-47 | Aquamarine Revenge (Well-Worn)",
    "AK-47 | Blue Laminate (Field-Tested)",
    "AK-47 | Breakthrough (Minimal Wear)",
    "AK-47 | Cartel (Factory New)",
    "AK-47 | Cartel (Minimal Wear)",
    "AK-47 | Crane Flight (Field-Tested)",
    "AK-47 | Emerald Pinstripe (Field-Tested)",
    "AK-47 | Frontside Misty (Minimal Wear)",
    "AK-47 | Head Shot (Battle-Scarred)",
    "AK-47 | Ice Coaled (Battle-Scarred)",
    "AK-47 | Ice Coaled (Factory New)",
    "AK-47 | Inheritance (Battle-Scarred)",
    "AK-47 | Midnight Laminate (Minimal Wear)",
    "AK-47 | Neon Rider (Minimal Wear)",
    "AK-47 | Nightwish (Battle-Scarred)",
    "AK-47 | Nightwish (Well-Worn)",
    "AK-47 | Nouveau Rouge (Minimal Wear)",
    "AK-47 | Orbit Mk01 (Field-Tested)",
    "AK-47 | Orbit Mk01 (Minimal Wear)",
    "AK-47 | Phantom Disruptor (Minimal Wear)",
    "AK-47 | Point Disarray (Factory New)",
    "AK-47 | Red Laminate (Field-Tested)",
    "AK-47 | Safari Mesh (Factory New)",
    "AK-47 | Safety Net (Field-Tested)",
    "AK-47 | Searing Rage (Battle-Scarred)",
    "AK-47 | Searing Rage (Factory New)",
    "AK-47 | Searing Rage (Field-Tested)",
    "AK-47 | The Oligarch (Field-Tested)",
    "AK-47 | The Outsiders (Field-Tested)",
    "AK-47 | Uncharted (Factory New)",
    "AK-47 | Wintergreen (Factory New)",
    "AK-47 | Wintergreen (Minimal Wear)",
    "AUG | Amber Slipstream (Factory New)",
    "AUG | Carved Jade (Minimal Wear)",
    "AUG | Chameleon (Field-Tested)",
    "AUG | Chameleon (Minimal Wear)",
    "AUG | Death by Puppy (Factory New)",
    "AUG | Death by Puppy (Field-Tested)",
    "AUG | Fleet Flock (Battle-Scarred)",
    "AUG | Fleet Flock (Field-Tested)",
    "AUG | Lil' Pig (Field-Tested)",
    "AUG | Luxe Trim (Factory New)",
    "AUG | Momentum (Field-Tested)",
    "AUG | Navy Murano (Well-Worn)",
    "AUG | Plague (Factory New)",
    "AUG | Spalted Wood (Factory New)",
    "AUG | Surveillance (Factory New)",
    "AUG | Syd Mead (Field-Tested)",
    "AUG | Triqua (Factory New)",
    "AWP | Acheron (Factory New)",
    "AWP | Atheris (Factory New)",
    "AWP | Atheris (Field-Tested)",
    "AWP | Black Nile (Factory New)",
    "AWP | Chromatic Aberration (Minimal Wear)",
    "AWP | Duality (Minimal Wear)",
    "AWP | Exoskeleton (Minimal Wear)",
    "AWP | Fever Dream (Factory New)",
    "AWP | Hyper Beast (Field-Tested)",
    "AWP | Hyper Beast (Well-Worn)",
    "AWP | POP AWP (Minimal Wear)",
    "AWP | Pink DDPAT (Field-Tested)",
    "AWP | Pink DDPAT (Minimal Wear)",
    "AWP | Redline (Field-Tested)",
    "AWP | Safari Mesh (Factory New)",
    "AWP | The End (Minimal Wear)",
    "AWP | Wildfire (Battle-Scarred)",
    "AWP | Wildfire (Field-Tested)",
    "AWP | Worm God (Factory New)",
    "CZ75-Auto | Circaetus (Factory New)",
    "CZ75-Auto | Distressed (Factory New)",
    "CZ75-Auto | Emerald (Factory New)",
    "CZ75-Auto | Imprint (Factory New)",
    "CZ75-Auto | Red Astor (Factory New)",
    "CZ75-Auto | Silver (Factory New)",
    "CZ75-Auto | Slalom (Factory New)",
    "CZ75-Auto | Tuxedo (Factory New)",
    "CZ75-Auto | Victoria (Minimal Wear)",
    "CZ75-Auto | Xiangliu (Factory New)",
    "Desert Eagle | Calligraffiti (Factory New)",
    "Desert Eagle | Code Red (Field-Tested)",
    "Desert Eagle | Conspiracy (Minimal Wear)",
    "Desert Eagle | Crimson Web (Field-Tested)",
    "Desert Eagle | Heat Treated (Factory New)",
    "Desert Eagle | Heat Treated (Minimal Wear)",
    "Desert Eagle | Heirloom (Minimal Wear)",
    "Desert Eagle | Light Rail (Factory New)",
    "Desert Eagle | Mecha Industries (Minimal Wear)",
    "Desert Eagle | Naga (Factory New)",
    "Desert Eagle | Ocean Drive (Battle-Scarred)",
    "Desert Eagle | Ocean Drive (Field-Tested)",
    "Desert Eagle | Printstream (Field-Tested)",
    "Desert Eagle | Sputnik (Factory New)",
    "Desert Eagle | The Bronze (Factory New)",
    "Dual Berettas | Demolition (Field-Tested)",
    "Dual Berettas | Elite 1.6 (Factory New)",
    "Dual Berettas | Heist (Factory New)",
    "Dual Berettas | Melondrama (Well-Worn)",
    "Dual Berettas | Panther (Factory New)",
    "Dual Berettas | Royal Consorts (Minimal Wear)",
    "Dual Berettas | Sweet Little Angels (Factory New)",
    "Dual Berettas | Sweet Little Angels (Field-Tested)",
    "Dual Berettas | Twin Turbo (Factory New)",
    "Dual Berettas | Twin Turbo (Minimal Wear)",
    "FAMAS | Bad Trip (Field-Tested)",
    "FAMAS | Commemoration (Field-Tested)",
    "FAMAS | Commemoration (Minimal Wear)",
    "FAMAS | Cyanospatter (Factory New)",
    "FAMAS | Dark Water (Minimal Wear)",
    "FAMAS | Faulty Wiring (Factory New)",
    "FAMAS | Night Borre (Minimal Wear)",
    "FAMAS | Pulse (Factory New)",
    "FAMAS | Rapid Eye Movement (Field-Tested)",
    "FAMAS | Rapid Eye Movement (Minimal Wear)",
    "FAMAS | Rapid Eye Movement (Well-Worn)",
    "FAMAS | Sergeant (Minimal Wear)",
    "FAMAS | Valence (Factory New)",
    "FAMAS | Yeti Camo (Factory New)",
    "Five-SeveN | Case Hardened (Minimal Wear)",
    "Five-SeveN | Copper Galaxy (Factory New)",
    "Five-SeveN | Fowl Play (Battle-Scarred)",
    "Five-SeveN | Heat Treated (Battle-Scarred)",
    "Five-SeveN | Heat Treated (Field-Tested)",
    "Five-SeveN | Retrobution (Factory New)",
    "Five-SeveN | Violent Daimyo (Factory New)",
    "Five-SeveN | Withered Vine (Factory New)",
    "Five-SeveN | Withered Vine (Field-Tested)",
    "G3SG1 | Flux (Field-Tested)",
    "Galil AR | Blue Titanium (Factory New)",
    "Galil AR | Connexion (Factory New)",
    "Galil AR | Control (Factory New)",
    "Galil AR | Crimson Tsunami (Factory New)",
    "Galil AR | Kami (Factory New)",
    "Galil AR | Rocket Pop (Factory New)",
    "Galil AR | Signal (Factory New)",
    "Glock-18 | Bunsen Burner (Factory New)",
    "Glock-18 | Catacombs (Factory New)",
    "Glock-18 | Clear Polymer (Factory New)",
    "Glock-18 | Grinder (Minimal Wear)",
    "Glock-18 | Ironwork (Factory New)",
    "Glock-18 | Mirror Mosaic (Battle-Scarred)",
    "Glock-18 | Mirror Mosaic (Well-Worn)",
    "Glock-18 | Neo-Noir (Well-Worn)",
    "Glock-18 | Snack Attack (Minimal Wear)",
    "Glock-18 | Vogue (Minimal Wear)",
    "Glock-18 | Water Elemental (Field-Tested)",
    "Glock-18 | Water Elemental (Minimal Wear)",
    "Glock-18 | Weasel (Factory New)",
    "Glock-18 | Winterized (Factory New)",
    "M4A1-S | Atomic Alloy (Minimal Wear)",
    "M4A1-S | Basilisk (Minimal Wear)",
    "M4A1-S | Blood Tiger (Factory New)",
    "M4A1-S | Blood Tiger (Minimal Wear)",
    "M4A1-S | Control Panel (Field-Tested)",
    "M4A1-S | Flashback (Battle-Scarred)",
    "M4A1-S | Flashback (Field-Tested)",
    "M4A1-S | Glitched Paint (Factory New)",
    "M4A1-S | Leaded Glass (Minimal Wear)",
    "M4A1-S | Party Animal (Factory New)",
    "M4A1-S | Player Two (Field-Tested)",
    "M4A1-S | Vaporwave (Field-Tested)",
    "M4A4 | Bullet Rain (Field-Tested)",
    "M4A4 | Choppa (Factory New)",
    "M4A4 | Cyber Security (Field-Tested)",
    "M4A4 | Desert-Strike (Field-Tested)",
    "M4A4 | Desert-Strike (Minimal Wear)",
    "M4A4 | Evil Daimyo (Factory New)",
    "M4A4 | Evil Daimyo (Field-Tested)",
    "M4A4 | Faded Zebra (Minimal Wear)",
    "M4A4 | Hellish (Well-Worn)",
    "M4A4 | Jungle Tiger (Minimal Wear)",
    "M4A4 | Magnesium (Factory New)",
    "M4A4 | Neo-Noir (Battle-Scarred)",
    "M4A4 | Neo-Noir (Field-Tested)",
    "M4A4 | Neo-Noir (Minimal Wear)",
    "M4A4 | The Emperor (Field-Tested)",
    "M4A4 | The Emperor (Minimal Wear)",
    "M4A4 | Turbine (Factory New)",
    "M4A4 | Turbine (Minimal Wear)",
    "M4A4 | 龍王 (Dragon King) (Minimal Wear)",
    "MAC-10 | Carnivore (Factory New)",
    "MAC-10 | Fade (Factory New)",
    "MAC-10 | Heat (Factory New)",
    "MAC-10 | Malachite (Factory New)",
    "MAC-10 | Propaganda (Field-Tested)",
    "MAC-10 | Sienna Damask (Factory New)",
    "MAC-10 | Surfwood (Factory New)",
    "MAC-10 | Surfwood (Field-Tested)",
    "MAC-10 | Toybox (Minimal Wear)",
    "MAG-7 | Bulldozer (Minimal Wear)",
    "MAG-7 | Monster Call (Factory New)",
    "MAG-7 | Navy Sheen (Factory New)",
    "MAG-7 | SWAG-7 (Factory New)",
    "MAG-7 | Silver (Factory New)",
    "MP5-SD | Agent (Factory New)",
    "MP5-SD | Desert Strike (Factory New)",
    "MP5-SD | Phosphor (Field-Tested)",
    "MP5-SD | Phosphor (Minimal Wear)",
    "MP7 | Abyssal Apparition (Battle-Scarred)",
    "MP7 | Armor Core (Factory New)",
    "MP7 | Astrolabe (Factory New)",
    "MP7 | Fade (Minimal Wear)",
    "MP7 | Impire (Factory New)",
    "MP7 | Nemesis (Factory New)",
    "MP7 | Prey (Factory New)",
    "MP7 | Scorched (Field-Tested)",
    "MP7 | Tall Grass (Factory New)",
    "MP9 | Airlock (Factory New)",
    "MP9 | Arctic Tri-Tone (Factory New)",
    "MP9 | Deadly Poison (Factory New)",
    "MP9 | Food Chain (Well-Worn)",
    "MP9 | Hydra (Minimal Wear)",
    "MP9 | Latte Rush (Field-Tested)",
    "MP9 | Music Box (Factory New)",
    "MP9 | Music Box (Field-Tested)",
    "MP9 | Orange Peel (Factory New)",
    "MP9 | Rose Iron (Factory New)",
    "MP9 | Ruby Poison Dart (Factory New)",
    "MP9 | Sand Dashed (Factory New)",
    "MP9 | Setting Sun (Factory New)",
    "MP9 | Setting Sun (Minimal Wear)",
    "MP9 | Starlight Protector (Battle-Scarred)",
    "MP9 | Urban Sovereign (Factory New)",
    "Negev | Nuclear Waste (Minimal Wear)",
    "Negev | Phoenix Stencil (Factory New)",
    "Nova | Green Apple (Factory New)",
    "Nova | Red Quartz (Field-Tested)",
    "Nova | Rising Skull (Factory New)",
    "Nova | Rising Sun (Factory New)",
    "Nova | Sobek's Bite (Field-Tested)",
    "Nova | Yorkshire (Factory New)",
    "P2000 | Dispatch (Factory New)",
    "P2000 | Imperial Dragon (Battle-Scarred)",
    "P2000 | Imperial Dragon (Minimal Wear)",
    "P2000 | Panther Camo (Minimal Wear)",
    "P2000 | Space Race (Factory New)",
    "P2000 | Turf (Factory New)",
    "P250 | Bengal Tiger (Minimal Wear)",
    "P250 | Black & Tan (Factory New)",
    "P250 | Boreal Forest (Factory New)",
    "P250 | Cartel (Field-Tested)",
    "P250 | Contaminant (Factory New)",
    "P250 | Digital Architect (Factory New)",
    "P250 | Epicenter (Field-Tested)",
    "P250 | Franklin (Factory New)",
    "P250 | Kintsugi (Field-Tested)",
    "P250 | Mehndi (Battle-Scarred)",
    "P250 | Mehndi (Minimal Wear)",
    "P250 | Muertos (Factory New)",
    "P250 | Muertos (Field-Tested)",
    "P250 | Nevermore (Factory New)",
    "P250 | Steel Disruption (Factory New)",
    "P250 | Supernova (Factory New)",
    "P250 | Vino Primo (Minimal Wear)",
    "P250 | Visions (Field-Tested)",
    "P90 | Ancient Earth (Well-Worn)",
    "P90 | Attack Vector (Minimal Wear)",
    "P90 | Chopper (Factory New)",
    "P90 | Deathgaze (Minimal Wear)",
    "P90 | Deathgaze (Well-Worn)",
    "P90 | Elite Build (Factory New)",
    "P90 | Glacier Mesh (Minimal Wear)",
    "P90 | Module (Factory New)",
    "P90 | Nostalgia (Field-Tested)",
    "P90 | Nostalgia (Minimal Wear)",
    "P90 | ScaraB Rush (Factory New)",
    "P90 | Shapewood (Field-Tested)",
    "P90 | Storm (Minimal Wear)",
    "P90 | Traction (Factory New)",
    "PP-Bizon | Bamboo Print (Factory New)",
    "PP-Bizon | Brass (Factory New)",
    "PP-Bizon | Chemical Green (Factory New)",
    "PP-Bizon | Fuel Rod (Factory New)",
    "PP-Bizon | Lumen (Factory New)",
    "PP-Bizon | Urban Dashed (Factory New)",
    "R8 Revolver | Bone Forged (Factory New)",
    "R8 Revolver | Fade (Field-Tested)",
    "R8 Revolver | Fade (Minimal Wear)",
    "R8 Revolver | Tango (Factory New)",
    "SCAR-20 | Cardiac (Field-Tested)",
    "SG 553 | Barricade (Factory New)",
    "SG 553 | Colony IV (Field-Tested)",
    "SG 553 | Danger Close (Factory New)",
    "SG 553 | Dragon Tech (Factory New)",
    "SG 553 | Fallout Warning (Factory New)",
    "SG 553 | Pulse (Minimal Wear)",
    "SG 553 | Ultraviolet (Minimal Wear)",
    "SSG 08 | Big Iron (Field-Tested)",
    "SSG 08 | Big Iron (Minimal Wear)",
    "SSG 08 | Blood in the Water (Minimal Wear)",
    "SSG 08 | Bloodshot (Field-Tested)",
    "SSG 08 | Dark Water (Field-Tested)",
    "SSG 08 | Dark Water (Minimal Wear)",
    "SSG 08 | Death's Head (Factory New)",
    "SSG 08 | Death's Head (Field-Tested)",
    "SSG 08 | Detour (Factory New)",
    "SSG 08 | Fever Dream (Factory New)",
    "SSG 08 | Parallax (Factory New)",
    "SSG 08 | Red Stone (Minimal Wear)",
    "SSG 08 | Spring Twilly (Factory New)",
    "SSG 08 | Threat Detected (Factory New)",
    "Sawed-Off | Bamboo Shadow (Factory New)",
    "Sawed-Off | Kiss♥Love (Field-Tested)",
    "Tec-9 | Brother (Factory New)",
    "Tec-9 | Fuel Injector (Field-Tested)",
    "Tec-9 | Groundwater (Factory New)",
    "Tec-9 | Toxic (Factory New)",
    "Tec-9 | Whiteout (Field-Tested)",
    "UMP-45 | Blaze (Factory New)",
    "UMP-45 | Continuum (Factory New)",
    "UMP-45 | Exposure (Factory New)",
    "UMP-45 | K.O. Factory (Factory New)",
    "UMP-45 | Primal Saber (Factory New)",
    "UMP-45 | Primal Saber (Field-Tested)",
    "UMP-45 | Scaffold (Factory New)",
    "UMP-45 | Wild Child (Battle-Scarred)",
    "UMP-45 | Wild Child (Minimal Wear)",
    "USP-S | Black Lotus (Minimal Wear)",
    "USP-S | Blueprint (Field-Tested)",
    "USP-S | Cortex (Battle-Scarred)",
    "USP-S | Cortex (Minimal Wear)",
    "USP-S | Cyrex (Minimal Wear)",
    "USP-S | Desert Tactical (Factory New)",
    "USP-S | Jawbreaker (Minimal Wear)",
    "USP-S | Lead Conduit (Factory New)",
    "USP-S | Printstream (Battle-Scarred)",
    "USP-S | Printstream (Field-Tested)",
    "USP-S | Purple DDPAT (Field-Tested)",
    "USP-S | Purple DDPAT (Minimal Wear)",
    "USP-S | Royal Blue (Field-Tested)",
    "USP-S | Royal Guard (Minimal Wear)",
    "USP-S | The Traitor (Battle-Scarred)",
    "USP-S | The Traitor (Minimal Wear)",
    "USP-S | Whiteout (Field-Tested)",
    "XM1014 | Entombed (Factory New)",
    "XM1014 | Scumbria (Factory New)",
    "XM1014 | XOXO (Factory New)",
]
