# Auto-generated by automation/nightly/run_model_backfill.py
# SOURCE_PY = 'C:\\Roman\\cs-skins-monitoring-bot\\automation_runtime\\model_backfill_queue_latest.py'
# N_OUTPUT_ITEMS = 1

ITEMS = [
    "AK-47 | Orbit Mk01 (Minimal Wear)",
]
