# Auto-generated by automation/nightly/run_model_backfill.py
# SOURCE_PY = '/home/runner/work/books/books/automation_runtime/model_backfill_queue_latest.py'
# N_OUTPUT_ITEMS = 2

ITEMS = [
    "MP7 | Army Recon (Factory New)",
    "Tec-9 | Remote Control (Minimal Wear)",
]
