# Auto-generated by automation/nightly/build_model_backfill_queue.py
# SOURCE_CSV = 'C:\\Roman\\cs-skins-monitoring-bot\\automation_runtime\\model_backfill_queue_latest.csv'
# N_OUTPUT_ITEMS = 27

ITEMS = [
    "AK-47 | Orbit Mk01 (Minimal Wear)",
    "AK-47 | Red Laminate (Field-Tested)",
    "AUG | Carved Jade (Minimal Wear)",
    "AUG | Navy Murano (Well-Worn)",
    "AWP | Pink DDPAT (Minimal Wear)",
    "CZ75-Auto | Emerald (Factory New)",
    "CZ75-Auto | Xiangliu (Factory New)",
    "Desert Eagle | Naga (Factory New)",
    "Desert Eagle | Ocean Drive (Battle-Scarred)",
    "Dual Berettas | Sweet Little Angels (Factory New)",
    "Five-SeveN | Fowl Play (Battle-Scarred)",
    "M4A1-S | Party Animal (Factory New)",
    "M4A4 | Bullet Rain (Field-Tested)",
    "MAC-10 | Propaganda (Field-Tested)",
    "MAG-7 | SWAG-7 (Factory New)",
    "MP9 | Airlock (Factory New)",
    "MP9 | Latte Rush (Field-Tested)",
    "MP9 | Music Box (Field-Tested)",
    "MP9 | Setting Sun (Factory New)",
    "P2000 | Panther Camo (Minimal Wear)",
    "P250 | Bengal Tiger (Minimal Wear)",
    "P250 | Mehndi (Minimal Wear)",
    "SG 553 | Ultraviolet (Minimal Wear)",
    "SSG 08 | Death's Head (Field-Tested)",
    "Tec-9 | Toxic (Factory New)",
    "UMP-45 | K.O. Factory (Factory New)",
    "USP-S | Purple DDPAT (Minimal Wear)",
]
