# Auto-generated by automation/nightly/run_model_backfill.py
# SOURCE_PY = '/home/runner/work/cs-skins-monitoring-bot/cs-skins-monitoring-bot/automation_runtime/model_backfill_queue_latest.py'
# N_OUTPUT_ITEMS = 1

ITEMS = [
    "P90 | Module (Factory New)",
]
